//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_x_address_mark
    {
        public int address_x_address_mark_id { get; set; }
        public int address_mark_id { get; set; }
        public int pxa_cxa_id { get; set; }
        public byte pxa_cxa_type_id { get; set; }
        public Nullable<bool> user_read { get; set; }
        public Nullable<bool> user_update { get; set; }
        public Nullable<bool> user_delete { get; set; }
        public Nullable<bool> user_change_status { get; set; }
        public Nullable<bool> user_change_priority { get; set; }
        public Nullable<bool> power_user_read { get; set; }
        public Nullable<bool> power_user_update { get; set; }
        public Nullable<bool> power_user_delete { get; set; }
        public Nullable<bool> power_user_change_status { get; set; }
        public Nullable<bool> power_user_change_priority { get; set; }
        public Nullable<bool> robot_change_status { get; set; }
        public Nullable<bool> robot_change_priority { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public int Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    
        public virtual address_mark address_mark { get; set; }
    }
}
