//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address_x_TimeZone
    {
        public int id { get; set; }
        public int Address_id { get; set; }
        public Nullable<int> TimeZone_id { get; set; }
    }
}
