//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public app_log()
        {
            this.app_log_client = new HashSet<app_log_client>();
        }
    
        public int app_log_id { get; set; }
        public string user_name { get; set; }
        public string address { get; set; }
        public string operation { get; set; }
        public System.DateTime operation_date { get; set; }
        public string description { get; set; }
        public System.DateTime operation_date_from { get; set; }
        public Nullable<System.DateTime> operation_date_to { get; set; }
        public Nullable<System.DateTime> login_date { get; set; }
        public Nullable<System.DateTime> logout_date { get; set; }
        public string session_id { get; set; }
        public Nullable<int> app_type_id { get; set; }
        public string service_version { get; set; }
        public string gui_version { get; set; }
        public string print_service_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<app_log_client> app_log_client { get; set; }
    }
}
