//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class auto_dial_agent_status
    {
        public int agent_id { get; set; }
        public int contr_id { get; set; }
        public System.DateTime date_start { get; set; }
        public string phone_in { get; set; }
        public string phone_out { get; set; }
        public short status { get; set; }
    }
}
