//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_statement_breakdown_item
    {
        public int bank_statement_breakdown_item_id { get; set; }
        public Nullable<int> bank_statement_breakdown_id { get; set; }
        public Nullable<int> bank_statement_breakdown_item_statute_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public Nullable<int> bank_account_id { get; set; }
        public Nullable<System.DateTime> bank_statement_breakdown_item_date { get; set; }
        public string bank_statement_breakdown_item_VS { get; set; }
        public Nullable<int> bank_statement_breakdown_items { get; set; }
        public Nullable<decimal> bank_statement_breakdown_items_balance { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
