//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_statement_credit_note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bank_statement_credit_note()
        {
            this.bank_statement_breakdown_credit_note = new HashSet<bank_statement_breakdown_credit_note>();
        }
    
        public int bank_statement_credit_note_id { get; set; }
        public int client_id { get; set; }
        public Nullable<int> statement_date_credit_note { get; set; }
        public Nullable<int> bank_statement_credit_note_statute_id { get; set; }
        public string filename { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public int Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bank_statement_breakdown_credit_note> bank_statement_breakdown_credit_note { get; set; }
    }
}
