//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_statement_breakdown_credit_note
    {
        public int bank_statement_breakdown_credit_note_id { get; set; }
        public Nullable<int> bank_statement_credit_note_id { get; set; }
        public Nullable<System.DateTime> credit_note_date { get; set; }
        public string credit_note_description { get; set; }
        public string credit_note_text { get; set; }
        public Nullable<long> invoice_id { get; set; }
        public string credit_note_variable_symbol { get; set; }
        public Nullable<decimal> credit_note_money { get; set; }
        public Nullable<byte> credit_note_assigned { get; set; }
        public Nullable<byte> bank_statement_breakdown_credit_note_statute_id { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    
        public virtual bank_statement_credit_note bank_statement_credit_note { get; set; }
    }
}
