//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_statement_breakdown_item_breakdown
    {
        public int bank_statement_breakdown_item_breakdown_id { get; set; }
        public Nullable<int> bank_statement_breakdown_id { get; set; }
        public Nullable<int> bank_statement_breakdown_item_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public Nullable<int> bank_account_id { get; set; }
        public Nullable<int> fix_bank_statement_breakdown_item_breakdown_id { get; set; }
        public Nullable<int> fix_payment_id { get; set; }
        public Nullable<int> bank_statement_breakdown_item_breakdown_record_type_id { get; set; }
        public Nullable<int> item_number { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> post_number { get; set; }
        public Nullable<int> postal_recipt_number { get; set; }
        public Nullable<System.DateTime> recipt_date { get; set; }
        public string variable_symnbol { get; set; }
        public string konstant_sysmbol { get; set; }
        public string specific_symbol { get; set; }
        public string Sender_info { get; set; }
        public string sender_message { get; set; }
        public Nullable<int> payment_assigned { get; set; }
        public Nullable<int> bank_statement_breakdown_item_breakdown_statute_id { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
