//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeepTask
    {
        public int ID { get; set; }
        public Nullable<int> QueueID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Delete { get; set; }
    }
}
