//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_E_mails_send
    {
        public int E_mails_send_id { get; set; }
        public int Debtor_id { get; set; }
        public int E_mail_id { get; set; }
        public int Status { get; set; }
        public string Sender { get; set; }
        public int Client_E_mail_text_id { get; set; }
        public int PrintsQueue_Items_id { get; set; }
    }
}
