//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PrintsQueue_Items_cases
    {
        public int PrintsQueue_Items_cases_id { get; set; }
        public int PrintsQueue_id { get; set; }
        public int Debtor_id { get; set; }
        public int PrintsQueue_Items_id { get; set; }
        public int case_id { get; set; }
    }
}
