//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PrintsLetter_doc
    {
        public int PrintsLetter_doc_id { get; set; }
        public int PrintsLetter_id { get; set; }
        public int PrintsTemplate_id { get; set; }
    }
}
