//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class @case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @case()
        {
            this.case_attribute = new HashSet<case_attribute>();
            this.case_return = new HashSet<case_return>();
            this.case_view_log = new HashSet<case_view_log>();
            this.case_x_debtor = new HashSet<case_x_debtor>();
            this.case_x_department = new HashSet<case_x_department>();
            this.case_x_department_x_user = new HashSet<case_x_department_x_user>();
            this.claims_payments = new HashSet<claims_payments>();
            this.contact = new HashSet<contact>();
            this.credit_note = new HashSet<credit_note>();
            this.installment = new HashSet<installment>();
            this.invoice1 = new HashSet<invoice>();
            this.payment = new HashSet<payment>();
            this.promise_payment = new HashSet<promise_payment>();
            this.splatka = new HashSet<splatka>();
        }
    
        public int case_id { get; set; }
        public Nullable<int> CaseSubPackage_id { get; set; }
        public Nullable<int> CasePackage_id { get; set; }
        public Nullable<int> Contract_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> debtor_id { get; set; }
        public Nullable<int> guarantor_id { get; set; }
        public Nullable<byte> case_statute_id { get; set; }
        public Nullable<long> ref_number { get; set; }
        public string client_ref_number { get; set; }
        public string payment_var_symbol { get; set; }
        public string payment_specific_symbol { get; set; }
        public Nullable<int> bank_account_id { get; set; }
        public Nullable<int> operator1_id { get; set; }
        public Nullable<int> operator2_id { get; set; }
        public Nullable<int> operator_group_id { get; set; }
        public Nullable<decimal> original_administrative_assessment { get; set; }
        public Nullable<decimal> administrative_assessment { get; set; }
        public Nullable<byte> invoice { get; set; }
        public Nullable<int> date_issued { get; set; }
        public Nullable<int> due_date { get; set; }
        public Nullable<byte> currency_id { get; set; }
        public Nullable<decimal> original_exchange_rate { get; set; }
        public Nullable<decimal> original_capital { get; set; }
        public Nullable<decimal> original_capital_czk { get; set; }
        public Nullable<decimal> actual_capital { get; set; }
        public Nullable<decimal> delay_charge_to_date_of_delivery { get; set; }
        public Nullable<decimal> delay_charge_actual { get; set; }
        public string case_text { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<byte> Delete_statute { get; set; }
        public Nullable<int> debtor_id_old { get; set; }
        public Nullable<byte> department_id { get; set; }
        public Nullable<int> master_case_id { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> case_id_old { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<case_attribute> case_attribute { get; set; }
        public virtual CasePackage CasePackage { get; set; }
        public virtual client client { get; set; }
        public virtual contract contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<case_return> case_return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<case_view_log> case_view_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<case_x_debtor> case_x_debtor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<case_x_department> case_x_department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<case_x_department_x_user> case_x_department_x_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claims_payments> claims_payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact> contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<credit_note> credit_note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installment> installment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promise_payment> promise_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<splatka> splatka { get; set; }
    }
}
