//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.administrative_assessment_settings = new HashSet<administrative_assessment_settings>();
            this.bank_account = new HashSet<bank_account>();
            this.@case = new HashSet<@case>();
            this.case_return = new HashSet<case_return>();
            this.CasePackage = new HashSet<CasePackage>();
            this.client_attribute = new HashSet<client_attribute>();
            this.contract = new HashSet<contract>();
            this.payment = new HashSet<payment>();
            this.payment_reported = new HashSet<payment_reported>();
        }
    
        public int client_id { get; set; }
        public Nullable<int> Persons_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public Nullable<int> PxA_id { get; set; }
        public Nullable<int> CxA_id { get; set; }
        public Nullable<int> client_type_id { get; set; }
        public Nullable<int> contact_Persons_id { get; set; }
        public Nullable<int> contact2_Persons_id { get; set; }
        public Nullable<int> primary_payment_account_id { get; set; }
        public string description { get; set; }
        public bool delay_charge { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public int Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public Nullable<int> return_limit { get; set; }
        public int max_return_limit { get; set; }
        public short fall_to_secondary { get; set; }
        public short limit_letter_to_secondary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<administrative_assessment_settings> administrative_assessment_settings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bank_account> bank_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@case> @case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<case_return> case_return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasePackage> CasePackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_attribute> client_attribute { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract> contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_reported> payment_reported { get; set; }
    }
}
