//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_description
    {
        public int client_description_id { get; set; }
        public int identity_id { get; set; }
        public int identity_type_id { get; set; }
        public string description_label { get; set; }
        public string description_value { get; set; }
        public Nullable<int> description_value_data_type_id { get; set; }
        public bool is_valid { get; set; }
        public int description_order { get; set; }
        public Nullable<int> data_column_number { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
