//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_external_final
    {
        public int contact_external_final_id { get; set; }
        public string Own_id { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string Born_date { get; set; }
        public string Identification { get; set; }
        public string Identification2 { get; set; }
        public string Street_original { get; set; }
        public string City_original { get; set; }
        public string Zip_original { get; set; }
        public string Phone_number_original { get; set; }
        public string Phone_number2_original { get; set; }
        public string Phone_number3_original { get; set; }
        public string Phone_number4_original { get; set; }
        public string Email_original { get; set; }
        public string Client { get; set; }
        public string Cpop { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Phone_number { get; set; }
        public string Phone_number2 { get; set; }
        public string Phone_number3 { get; set; }
        public string Phone_number4 { get; set; }
        public string Email { get; set; }
        public Nullable<int> address_statute { get; set; }
        public Nullable<int> address_statute_in_db { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public int Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
