//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contract()
        {
            this.@case = new HashSet<@case>();
            this.CasePackage = new HashSet<CasePackage>();
        }
    
        public int contract_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> contract_number { get; set; }
        public Nullable<System.DateTime> signature_date { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public Nullable<int> operator_id { get; set; }
        public Nullable<int> client_persons_id { get; set; }
        public Nullable<int> responsible_persons_id { get; set; }
        public Nullable<decimal> initial_assessment { get; set; }
        public Nullable<decimal> subscription_above { get; set; }
        public Nullable<int> due_date_of_next_subscription_above { get; set; }
        public Nullable<short> subscription_paid { get; set; }
        public Nullable<int> due_date_of_initial_assessment { get; set; }
        public Nullable<short> initial_assessment_paid { get; set; }
        public Nullable<double> late_interest { get; set; }
        public Nullable<System.DateTime> letter_of_attorney_date_1 { get; set; }
        public Nullable<System.DateTime> letter_of_attorney_date_2 { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@case> @case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasePackage> CasePackage { get; set; }
        public virtual client client { get; set; }
    }
}
