//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cost
    {
        public int cost_id { get; set; }
        public Nullable<System.DateTime> cost_date { get; set; }
        public int cost_type { get; set; }
        public string cost_document { get; set; }
        public decimal cost_price { get; set; }
        public short cost_DPH_Type { get; set; }
        public decimal cost_dph { get; set; }
        public decimal cost_full_price { get; set; }
        public Nullable<decimal> cost_time { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
