//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_note
    {
        public int credit_note_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> CasePackage_id { get; set; }
        public Nullable<int> Contract_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<decimal> original_exchange_rate { get; set; }
        public Nullable<decimal> credit_note_capital { get; set; }
        public Nullable<decimal> credit_note_capital_czk { get; set; }
        public Nullable<decimal> credit_note_capital_delay_charge { get; set; }
        public string credit_note_text { get; set; }
        public string credit_note_description { get; set; }
        public Nullable<System.DateTime> credit_note_date { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public Nullable<int> outside_id { get; set; }
        public Nullable<int> id_bank_statement { get; set; }
        public Nullable<int> slave_case_id { get; set; }
        public Nullable<int> bank_statement_breakdown_credit_note_id { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual invoice invoice { get; set; }
    }
}
