//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_news
    {
        public int db_news_id { get; set; }
        public Nullable<System.DateTime> db_news_date { get; set; }
        public string db_news_type { get; set; }
        public string db_news_client { get; set; }
        public string db_news_text { get; set; }
        public Nullable<byte> db_news_sent_to_people { get; set; }
        public Nullable<System.DateTime> db_news_sent_to_people_date { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
    }
}
