//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class debthor_err_log
    {
        public int debthor_err_log_id { get; set; }
        public string flex_client_id { get; set; }
        public string error_string { get; set; }
        public string browser_user_agent { get; set; }
        public string fp_version { get; set; }
        public string operating_system { get; set; }
        public Nullable<int> debug_version { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
    }
}
