//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class debtor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public debtor()
        {
            this.bonita = new HashSet<bonita>();
        }
    
        public int debtor_id { get; set; }
        public Nullable<int> Persons_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public Nullable<int> PxA_id { get; set; }
        public Nullable<int> CxA_id { get; set; }
        public Nullable<byte> debtor_type_id { get; set; }
        public Nullable<int> contact_Persons_id { get; set; }
        public Nullable<int> contact2_Persons_id { get; set; }
        public Nullable<short> primary_payment_account_id { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public Nullable<int> persons_id_old { get; set; }
        public Nullable<int> company_id_old { get; set; }
        public Nullable<int> debtor_id_dedupl { get; set; }
        public Nullable<int> PxA_id_old { get; set; }
        public Nullable<int> CxA_id_old { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bonita> bonita { get; set; }
    }
}
