//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dictionary
    {
        public int id { get; set; }
        public string container { get; set; }
        public string identifier { get; set; }
        public string property { get; set; }
        public string cz { get; set; }
        public string sk { get; set; }
        public string ru { get; set; }
    }
}
