//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class emails
    {
        public int emails_id { get; set; }
        public Nullable<int> emails_package_id { get; set; }
        public Nullable<int> prints_aplications_id { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> CasePackage_id { get; set; }
        public Nullable<int> Contract_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> debtor_id { get; set; }
        public string email_from { get; set; }
        public string email_to { get; set; }
        public string email_subject { get; set; }
        public byte[] email_body { get; set; }
        public bool send { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<byte> Delete_statute { get; set; }
    }
}
