//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class et
    {
        public int et_id { get; set; }
        public string et_number { get; set; }
        public short et_type { get; set; }
        public Nullable<System.DateTime> et_date_from { get; set; }
        public Nullable<System.DateTime> et_date_legal_validity { get; set; }
        public Nullable<System.DateTime> et_date_executable { get; set; }
        public Nullable<int> et_issued_by { get; set; }
        public Nullable<decimal> et_priznano_priznany_narok { get; set; }
        public Nullable<decimal> et_priznano_pevne_uroky { get; set; }
        public Nullable<decimal> et_priznano_poplatky_z_prodleni { get; set; }
        public Nullable<decimal> et_priznano_uroky_z_prodleni { get; set; }
        public Nullable<decimal> et_priznano_naklady_opravneneho { get; set; }
        public Nullable<decimal> et_priznano_naklady_prav_zastupce { get; set; }
        public Nullable<decimal> et_uhrazeno_priznany_narok { get; set; }
        public Nullable<decimal> et_uhrazeno_pevne_uroky { get; set; }
        public Nullable<decimal> et_uhrazeno_poplatky_z_prodleni { get; set; }
        public Nullable<decimal> et_uhrazeno_uroky_z_prodleni { get; set; }
        public Nullable<decimal> et_uhrazeno_naklady_opravneneho { get; set; }
        public Nullable<decimal> et_uhrazeno_naklady_prav_zastupce { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<decimal> et_priznano_smluvni_pokuta { get; set; }
        public Nullable<decimal> et_priznano_soudni_spravni_poplatek { get; set; }
        public Nullable<decimal> et_priznano_neprirazena_platba { get; set; }
        public Nullable<decimal> et_priznano_penale { get; set; }
        public Nullable<decimal> et_uhrazeno_smluvni_pokuta { get; set; }
        public Nullable<decimal> et_uhrazeno_soudni_spravni_poplatek { get; set; }
        public Nullable<decimal> et_uhrazeno_neprirazena_platba { get; set; }
        public Nullable<decimal> et_uhrazeno_penale { get; set; }
    }
}
