//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class forms_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public forms_items()
        {
            this.forms_items_properities = new HashSet<forms_items_properities>();
        }
    
        public int forms_items_id { get; set; }
        public Nullable<int> forms_list_id { get; set; }
        public Nullable<int> forms_parts_id { get; set; }
        public Nullable<int> forms_items_event_id { get; set; }
        public string forms_items_name { get; set; }
    
        public virtual forms_list forms_list { get; set; }
        public virtual forms_parts forms_parts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forms_items_properities> forms_items_properities { get; set; }
    }
}
