//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class guarantor
    {
        public int guarantor_id { get; set; }
        public Nullable<int> Persons_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public Nullable<int> PxA_id { get; set; }
        public Nullable<int> CxA_id { get; set; }
        public Nullable<int> guarantor_type_id { get; set; }
        public Nullable<int> contact_Persons_id { get; set; }
        public Nullable<int> contact2_Persons_id { get; set; }
        public Nullable<int> primary_payment_account_id { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public int Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
