//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_data_contact
    {
        public int import_data_contact_id { get; set; }
        public Nullable<int> import_data_id { get; set; }
        public Nullable<int> imports_id { get; set; }
        public string client_ref_number { get; set; }
        public Nullable<int> contact_type_id { get; set; }
        public Nullable<int> status_type_id { get; set; }
        public Nullable<System.DateTime> contact_date { get; set; }
        public Nullable<int> operator_id { get; set; }
        public string contact_text { get; set; }
        public string contact_client_text { get; set; }
        public string description { get; set; }
        public Nullable<int> future_contact_type_id { get; set; }
        public Nullable<System.DateTime> future_contact_date { get; set; }
        public string future_contact_text { get; set; }
        public string future_contact_client_text { get; set; }
        public string future_contact_description { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
