//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_payment_step
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public import_payment_step()
        {
            this.ipm_x_ips = new HashSet<ipm_x_ips>();
        }
    
        public int id_import_payment_steps { get; set; }
        public string step_name { get; set; }
        public string step_definition { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string node_key { get; set; }
        public int image_index { get; set; }
        public bool import_step { get; set; }
        public bool check_step { get; set; }
        public string check_column { get; set; }
        public bool scalar_step { get; set; }
        public bool extract_file_name_step { get; set; }
        public bool extract_column_name_step { get; set; }
        public int extract_column_index { get; set; }
        public bool write_to_db { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ipm_x_ips> ipm_x_ips { get; set; }
    }
}
