//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class imports
    {
        public int imports_id { get; set; }
        public Nullable<int> Client_id { get; set; }
        public Nullable<int> Contract_id { get; set; }
        public Nullable<int> CasePackage_id { get; set; }
        public Nullable<System.DateTime> migration_start_date { get; set; }
        public Nullable<int> imported { get; set; }
        public Nullable<int> imported_by { get; set; }
        public Nullable<System.DateTime> imported_date { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public int Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
