//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_desc
    {
        public int import_desc_id { get; set; }
        public Nullable<int> import_type_id { get; set; }
        public Nullable<int> row_id { get; set; }
        public string source_field { get; set; }
        public string destination_field { get; set; }
        public Nullable<int> relative_position { get; set; }
        public Nullable<int> characters { get; set; }
    }
}
