//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspector
    {
        public int inspector_id { get; set; }
        public Nullable<int> Persons_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public Nullable<int> PxA_id { get; set; }
        public Nullable<int> CxA_id { get; set; }
        public Nullable<int> users_id { get; set; }
        public byte inspector_type_id { get; set; }
        public string prideleny_kod { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public Nullable<int> master_inspector_id { get; set; }
    }
}
