//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class institution
    {
        public int institution_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public int institution_type { get; set; }
        public string institution_name { get; set; }
        public string institution_name2p { get; set; }
        public string institution_name3p { get; set; }
        public string institution_name4p { get; set; }
        public string institution_street { get; set; }
        public string institution_city { get; set; }
        public string institution_zip { get; set; }
        public string institution_phone { get; set; }
        public string institution_email { get; set; }
        public string institution_fax { get; set; }
        public string institution_street6p { get; set; }
        public string institution_city6p { get; set; }
        public Nullable<short> DPH { get; set; }
        public Nullable<int> bank_account_id { get; set; }
        public string property1 { get; set; }
        public string property2 { get; set; }
        public string property3 { get; set; }
        public string property4 { get; set; }
        public string property5 { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
