//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class installment_settings
    {
        public int installment_settings_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> contract_id { get; set; }
        public Nullable<int> casepackage_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<byte> include_actual_capital { get; set; }
        public Nullable<byte> include_delay_charge_actual { get; set; }
        public Nullable<byte> include_administrative_assessment { get; set; }
        public Nullable<int> payments { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public Nullable<int> pay_period_increment { get; set; }
        public string pay_period { get; set; }
        public Nullable<int> round { get; set; }
        public Nullable<int> bank_id { get; set; }
        public Nullable<int> bank_account_id { get; set; }
        public Nullable<byte> include_administrative_assessment_separate { get; set; }
        public Nullable<int> bank_id_administrative_assessment { get; set; }
        public Nullable<int> bank_account_id_administrative_assessment { get; set; }
        public Nullable<int> contact_type_id { get; set; }
        public Nullable<int> print_aplications_id { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
