//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class installment_breakdown_temp
    {
        public int installment_breakdown_temp_id { get; set; }
        public Nullable<short> payment_number { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public Nullable<decimal> payment { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
    }
}
