//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int inventory_id { get; set; }
        public int computer_id { get; set; }
        public string SW_vendor { get; set; }
        public string SW_name { get; set; }
        public string SW_version { get; set; }
        public string SW_description { get; set; }
        public Nullable<byte> SW_license_needed { get; set; }
    }
}
