//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ipm_x_ips
    {
        public int id_import_payment_method_x_import_payment_step { get; set; }
        public int import_payment_method_id { get; set; }
        public int import_payment_step_id { get; set; }
        public int step_index { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public bool enable { get; set; }
    
        public virtual import_payment_method import_payment_method { get; set; }
        public virtual import_payment_step import_payment_step { get; set; }
    }
}
