//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class libs_items_dict
    {
        public int libs_items_id { get; set; }
        public int libs_id { get; set; }
        public string libs_main_libs_id { get; set; }
        public string lib_value { get; set; }
        public string l1 { get; set; }
        public string l2 { get; set; }
        public string l3 { get; set; }
        public string lib_order { get; set; }
        public string libs_main_lib_value { get; set; }
    }
}
