//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobilni_predvolby
    {
        public int mobilni_predvolby_id { get; set; }
        public string predvolba_old { get; set; }
        public Nullable<short> predvolba { get; set; }
        public string Operator { get; set; }
    }
}
