//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_address_cashe
    {
        public int new_address_cashe_id { get; set; }
        public Nullable<int> persons_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string cpop { get; set; }
        public string cor { get; set; }
        public Nullable<byte> xA_type { get; set; }
        public Nullable<byte> xA_status { get; set; }
        public string Address_street { get; set; }
        public string Address_street2 { get; set; }
        public string Address_village { get; set; }
        public string Address_city { get; set; }
        public string Address_zip { get; set; }
        public string Address_Country { get; set; }
        public byte status { get; set; }
        public string okres { get; set; }
        public string region { get; set; }
    }
}
