//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class okresy_a_kraje
    {
        public int okresy_a_kraje_id { get; set; }
        public string psc { get; set; }
        public string obec { get; set; }
        public string okres { get; set; }
        public string kraj { get; set; }
        public Nullable<int> soud_id { get; set; }
        public string CTU_kod { get; set; }
    }
}
