//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payment()
        {
            this.payment_breakdown1 = new HashSet<payment_breakdown>();
            this.payment_reported = new HashSet<payment_reported>();
        }
    
        public int payment_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> bank_statement_id { get; set; }
        public Nullable<int> bank_statement_breakdown_id { get; set; }
        public Nullable<int> bank_statement_breakdown_item_id { get; set; }
        public Nullable<int> bank_statement_breakdown_item_breakdown_id { get; set; }
        public Nullable<byte> payment_type_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<System.DateTime> bank_statement_date { get; set; }
        public string bank_statement_number { get; set; }
        public Nullable<short> bank_id { get; set; }
        public Nullable<int> bank_account_id { get; set; }
        public Nullable<byte> currency_id { get; set; }
        public Nullable<decimal> payed_capital { get; set; }
        public Nullable<decimal> original_exchange_rate { get; set; }
        public Nullable<decimal> payed_capital_czk { get; set; }
        public Nullable<decimal> payed_delay_charge { get; set; }
        public Nullable<decimal> payed_administrative_assessment { get; set; }
        public Nullable<decimal> payed_plus_money { get; set; }
        public string description { get; set; }
        public Nullable<byte> payment_breakdown { get; set; }
        public string invoice_number { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<byte> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public Nullable<int> slave_case_id { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_breakdown> payment_breakdown1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_reported> payment_reported { get; set; }
    }
}
