//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persons()
        {
            this.PxA = new HashSet<PxA>();
            this.PxC = new HashSet<PxC>();
            this.PxT = new HashSet<PxT>();
        }
    
        public int Persons_id { get; set; }
        public string Persons_title { get; set; }
        public string Persons_firstname { get; set; }
        public string Persons_surname { get; set; }
        public string Persons_born_name { get; set; }
        public string Persons_end_title { get; set; }
        public Nullable<byte> Persons_gender { get; set; }
        public Nullable<byte> Persons_born_day { get; set; }
        public Nullable<byte> Persons_born_month { get; set; }
        public Nullable<short> Persons_born_year { get; set; }
        public string Persons_born_number { get; set; }
        public string Persons_identity_card { get; set; }
        public Nullable<byte> Persons_id_mstatute { get; set; }
        public Nullable<byte> Persons_id_statute { get; set; }
        public string persons_description { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public Nullable<int> persons_id_dedupl { get; set; }
        public string persons_title2 { get; set; }
        public string persons_title3 { get; set; }
        public string persons_end_title2 { get; set; }
        public string persons_vokativ { get; set; }
        public string persons_addr { get; set; }
        public Nullable<byte> persons_do_not_display { get; set; }
        public string persons_nationality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PxA> PxA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PxC> PxC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PxT> PxT { get; set; }
    }
}
