//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons_log
    {
        public int Persons_log_id { get; set; }
        public Nullable<int> Persons_log_persons_id { get; set; }
        public string Persons_log_firstname { get; set; }
        public string Persons_log_surname { get; set; }
        public string Persons_log_born_name { get; set; }
        public Nullable<byte> Persons_log_born_day { get; set; }
        public Nullable<byte> Persons_log_born_month { get; set; }
        public Nullable<short> Persons_log_born_year { get; set; }
        public string Persons_log_born_number { get; set; }
        public string Persons_log_update_user { get; set; }
        public Nullable<System.DateTime> Persons_log_update_date { get; set; }
        public Nullable<System.DateTime> Persons_log_update_date_dbo { get; set; }
    }
}
