//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons_duplicated
    {
        public int Persons_duplicated_id { get; set; }
        public int Persons_id { get; set; }
        public int Persons_unique_id { get; set; }
    }
}
