//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone_code_replace
    {
        public int id { get; set; }
        public string old_code { get; set; }
        public string new_code { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
