//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class postal_order
    {
        public int postal_order_id { get; set; }
        public Nullable<int> postal_order_type_id { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> installment_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public string bank_account_number_owner_name { get; set; }
        public string bank_account_number_owner_street { get; set; }
        public string bank_account_number_owner_city { get; set; }
        public string bank_account_number_owner_zip { get; set; }
        public string bank_account { get; set; }
        public string bank { get; set; }
        public string tr_code { get; set; }
        public string postziro_code { get; set; }
        public string postziro_bank { get; set; }
        public string S_code { get; set; }
        public string Persons_title { get; set; }
        public string Persons_firstname { get; set; }
        public string Persons_surname { get; set; }
        public string Address_cpop { get; set; }
        public string Address_street { get; set; }
        public string Address_city { get; set; }
        public string Address_zip { get; set; }
        public string VS { get; set; }
        public string SS { get; set; }
        public string KS { get; set; }
        public Nullable<decimal> kc { get; set; }
        public Nullable<decimal> hal { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<byte> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
