//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class postal_order_temp
    {
        public int postal_order_temp_id { get; set; }
        public Nullable<int> postal_order_bank_id { get; set; }
        public Nullable<int> postal_order_bank_account_id { get; set; }
        public Nullable<int> postal_order_count { get; set; }
        public Nullable<int> postal_order_type_id { get; set; }
        public Nullable<decimal> postal_order_amount { get; set; }
        public string insert_user { get; set; }
    }
}
