//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class print_aplications_printer_setup
    {
        public int print_aplications_printer_setup_id { get; set; }
        public Nullable<int> print_aplications_id { get; set; }
        public Nullable<int> print_aplications_doc_id { get; set; }
        public Nullable<int> Copies { get; set; }
        public string DeviceName { get; set; }
        public string PaperBin { get; set; }
        public Nullable<int> duplex { get; set; }
        public string Orientation { get; set; }
        public string BottomMargin { get; set; }
        public string LeftMargin { get; set; }
        public string RightMargin { get; set; }
        public string TopMargin { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public int Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    
        public virtual print_aplications print_aplications { get; set; }
        public virtual print_aplications_doc print_aplications_doc { get; set; }
        public virtual print_aplications_doc print_aplications_doc1 { get; set; }
    }
}
