//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class print_aplications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public print_aplications()
        {
            this.print_aplications_doc = new HashSet<print_aplications_doc>();
            this.print_aplications_printer_setup = new HashSet<print_aplications_printer_setup>();
        }
    
        public int print_aplications_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> casepackage_id { get; set; }
        public string name { get; set; }
        public string report_name { get; set; }
        public Nullable<int> languague { get; set; }
        public Nullable<int> letter_no { get; set; }
        public Nullable<int> print_aplication_type_id { get; set; }
        public int contact_status_type_id { get; set; }
        public Nullable<int> paper_orientation { get; set; }
        public Nullable<int> default_paper { get; set; }
        public Nullable<int> duplex { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public int Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public Nullable<int> report_data_template_id { get; set; }
        public Nullable<int> report_template_id { get; set; }
        public string xml_id { get; set; }
        public int contact_type_id { get; set; }
        public Nullable<bool> print_OMR { get; set; }
        public Nullable<int> envelope_type_id { get; set; }
        public int Copies { get; set; }
        public Nullable<int> default_pa_id { get; set; }
        public int debtor_type { get; set; }
        public int ar_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<print_aplications_doc> print_aplications_doc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<print_aplications_printer_setup> print_aplications_printer_setup { get; set; }
    }
}
