//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class prints_aplications_UA2
    {
        public int prints_aplications_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> casepackage_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> prints_package_id { get; set; }
        public Nullable<int> prints_id { get; set; }
        public string name { get; set; }
        public string report_name { get; set; }
        public Nullable<byte> languague { get; set; }
        public Nullable<byte> print_aplication_type_id { get; set; }
        public Nullable<int> paper_orientation { get; set; }
        public Nullable<int> default_paper { get; set; }
        public Nullable<int> duplex { get; set; }
        public byte[] rerport_template_xml { get; set; }
        public Nullable<int> print_aplications_id { get; set; }
        public Nullable<int> print_aplications_doc_id { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<int> prints_spool_groupping_id { get; set; }
    }
}
