//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class print_aplications_doc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public print_aplications_doc()
        {
            this.print_aplications_printer_setup = new HashSet<print_aplications_printer_setup>();
            this.print_aplications_printer_setup1 = new HashSet<print_aplications_printer_setup>();
            this.prints_aplications = new HashSet<prints_aplications>();
        }
    
        public int print_aplications_doc_id { get; set; }
        public string print_aplications_doc_name { get; set; }
        public int print_aplications_id { get; set; }
        public int report_data_template_id { get; set; }
        public int report_template_id { get; set; }
        public string xml_id { get; set; }
        public Nullable<short> print_aplications_doc_order { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    
        public virtual print_aplications print_aplications { get; set; }
        public virtual report_data_template report_data_template { get; set; }
        public virtual report_template report_template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<print_aplications_printer_setup> print_aplications_printer_setup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<print_aplications_printer_setup> print_aplications_printer_setup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prints_aplications> prints_aplications { get; set; }
    }
}
