//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class prints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prints()
        {
            this.prints_rendered_doc = new HashSet<prints_rendered_doc>();
        }
    
        public int prints_id { get; set; }
        public Nullable<int> prints_package_id { get; set; }
        public Nullable<int> prints_aplications_id { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> installment_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> CasePackage_id { get; set; }
        public Nullable<int> Contract_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> debtor_id { get; set; }
        public Nullable<int> guarantor_id { get; set; }
        public Nullable<int> prints_group_id { get; set; }
        public Nullable<int> ref_number { get; set; }
        public Nullable<byte> operator1_id { get; set; }
        public Nullable<byte> operator2_id { get; set; }
        public Nullable<byte> operator_group_id { get; set; }
        public Nullable<byte> invoice { get; set; }
        public Nullable<int> date_issued { get; set; }
        public Nullable<int> due_date { get; set; }
        public Nullable<byte> currency_id { get; set; }
        public Nullable<decimal> original_exchange_rate { get; set; }
        public string client_ref_number { get; set; }
        public string payment_var_symbol { get; set; }
        public string payment_specific_symbol { get; set; }
        public string bank_account_id { get; set; }
        public Nullable<decimal> original_capital { get; set; }
        public Nullable<decimal> original_capital_czk { get; set; }
        public Nullable<decimal> actual_capital { get; set; }
        public Nullable<decimal> delay_charge_to_date_of_delivery { get; set; }
        public Nullable<decimal> delay_charge_actual { get; set; }
        public Nullable<decimal> administrative_assessment { get; set; }
        public string case_text { get; set; }
        public string Persons_address_general { get; set; }
        public string Persons_address_and_bornnumber { get; set; }
        public string address { get; set; }
        public string client { get; set; }
        public string operator_text { get; set; }
        public Nullable<int> operator_id { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public Nullable<byte> print_Aplication_id { get; set; }
        public string description { get; set; }
        public Nullable<byte> prints_type_id { get; set; }
        public byte[] report_data_xml { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<byte> Delete_statute { get; set; }
        public Nullable<int> PxA_id { get; set; }
        public Nullable<int> CxA_id { get; set; }
        public Nullable<int> printed_papers { get; set; }
        public Nullable<long> unique_doc_group_id { get; set; }
        public Nullable<bool> recalculate_delay_charge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prints_rendered_doc> prints_rendered_doc { get; set; }
    }
}
