//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class prints_spool_temp
    {
        public int prints_spool_temp_id { get; set; }
        public Nullable<int> prints_spool_id { get; set; }
        public Nullable<byte> send_to_printer { get; set; }
        public Nullable<int> prints_spool_groupping_id { get; set; }
    }
}
