//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provision_settings
    {
        public int Provision_settings_id { get; set; }
        public Nullable<int> Provision_main_settings_id { get; set; }
        public byte Provision_type_id { get; set; }
        public Nullable<short> Provision_category_id { get; set; }
        public Nullable<short> Provision_subcategory_id { get; set; }
        public Nullable<int> Provision_user_id { get; set; }
        public string Provision_source_table { get; set; }
        public string Provision_formula { get; set; }
        public Nullable<int> Provision_client_id { get; set; }
        public Nullable<int> Provision_contract_id { get; set; }
        public Nullable<int> Provision_CasePackage_id { get; set; }
        public Nullable<int> Provision_CaseSubPackage_id { get; set; }
        public Nullable<int> Provision_Case_id { get; set; }
        public Nullable<int> Provision_Invoice_id { get; set; }
        public Nullable<System.DateTime> Provision_validity_from { get; set; }
        public Nullable<System.DateTime> Provision_validity_to { get; set; }
        public string Provision_validity_formula { get; set; }
        public Nullable<byte> Provision_invoice_to_client { get; set; }
        public string Provision_invoice_text { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
    }
}
