//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PxA
    {
        public int PxA_id { get; set; }
        public int Persons_id { get; set; }
        public int Address_id { get; set; }
        public string cpop { get; set; }
        public string cor { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Source { get; set; }
        public Nullable<byte> Mailing_priority { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public byte priority { get; set; }
        public Nullable<int> address_id_old { get; set; }
        public Nullable<int> persons_id_old { get; set; }
        public Nullable<int> PxA_id_dedupl { get; set; }
        public string description { get; set; }
        public string parser_error { get; set; }
        public string original_address { get; set; }
        public string registry_address { get; set; }
        public Nullable<int> sektor { get; set; }
        public Nullable<int> kod_adr { get; set; }
        public Nullable<int> verifier_status_id { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
