//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PxC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PxC()
        {
            this.PxC_type = new HashSet<PxC_type>();
            this.PxC_x_CxA = new HashSet<PxC_x_CxA>();
        }
    
        public int PxC_id { get; set; }
        public int Persons_id { get; set; }
        public int Company_id { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Source { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public byte priority { get; set; }
        public Nullable<int> persons_id_old { get; set; }
        public Nullable<int> company_id_old { get; set; }
        public Nullable<int> PxC_id_dedupl { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> PxC_validity_from { get; set; }
        public Nullable<System.DateTime> PxC_validity_to { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Persons Persons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PxC_type> PxC_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PxC_x_CxA> PxC_x_CxA { get; set; }
    }
}
