//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PxC_x_CxA
    {
        public int PxC_x_CxA_id { get; set; }
        public Nullable<int> PxC_id { get; set; }
        public Nullable<int> CxA_id { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> validity_from { get; set; }
        public Nullable<System.DateTime> validity_to { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public byte Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public Nullable<int> PxC_id_old { get; set; }
        public Nullable<int> CxA_id_old { get; set; }
    
        public virtual CxA CxA { get; set; }
        public virtual PxC PxC { get; set; }
    }
}
