//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_money_flow
    {
        public int report_money_flow_id { get; set; }
        public Nullable<int> weeks { get; set; }
        public Nullable<int> batch { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<decimal> payed_money { get; set; }
        public Nullable<decimal> batch_total_capital { get; set; }
        public Nullable<double> percent_week { get; set; }
        public Nullable<decimal> payed_money_up_tp_week { get; set; }
        public Nullable<double> percent_up_to_week { get; set; }
    }
}
