//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_money_to_invoice_temp
    {
        public int report_money_to_invoice_temp_id { get; set; }
        public Nullable<int> report_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> ref_number { get; set; }
        public Nullable<int> to_transfer { get; set; }
        public Nullable<decimal> payed_capital { get; set; }
        public Nullable<decimal> payed_delay_charge { get; set; }
        public Nullable<decimal> payed_administrative_assessment { get; set; }
        public Nullable<decimal> capital_provision { get; set; }
        public Nullable<decimal> delay_charge_provision { get; set; }
        public Nullable<decimal> payed_administrative_assessment_provision { get; set; }
        public Nullable<decimal> total_provision { get; set; }
        public string insert_user { get; set; }
    }
}
