//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_success_batch_month_kalendarni
    {
        public Nullable<decimal> ALL_USPESNOST { get; set; }
        public Nullable<decimal> KAP_USPESNOST { get; set; }
        public Nullable<decimal> ADM_USPESNOST { get; set; }
        public Nullable<decimal> UROK_USPESNOST { get; set; }
        public int operator1_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> mesic { get; set; }
        public Nullable<int> rok { get; set; }
        public string user_name { get; set; }
        public Nullable<int> casepackage_ref_number { get; set; }
    }
}
