//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class robot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public robot()
        {
            this.robot_results = new HashSet<robot_results>();
            this.web_source_search_error = new HashSet<web_source_search_error>();
            this.web_source_search_result = new HashSet<web_source_search_result>();
        }
    
        public int robot_id { get; set; }
        public int type_id { get; set; }
        public int case_id { get; set; }
        public Nullable<int> debtor_id { get; set; }
        public int status { get; set; }
        public string parametr1 { get; set; }
        public string parametr2 { get; set; }
        public string parametr3 { get; set; }
        public string vystup1 { get; set; }
        public string vystup2 { get; set; }
        public string vystup3 { get; set; }
        public Nullable<System.DateTime> plan_time { get; set; }
        public Nullable<System.DateTime> exec_time { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<robot_results> robot_results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_source_search_error> web_source_search_error { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_source_search_result> web_source_search_result { get; set; }
    }
}
