//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class select_queue_items
    {
        public int select_queue_items_id { get; set; }
        public int select_queue_id { get; set; }
        public int case_id { get; set; }
        public int delete_statute { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public string delete_user { get; set; }
    }
}
