//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_out
    {
        public int sms_out_id { get; set; }
        public Nullable<long> msg_out_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> installment_id { get; set; }
        public Nullable<int> telecom_id { get; set; }
        public string msg_out_gate { get; set; }
        public string msg_out_number { get; set; }
        public string msg_out_text { get; set; }
        public Nullable<byte> msg_out_send { get; set; }
        public Nullable<System.DateTime> msg_out_send_date { get; set; }
        public Nullable<System.DateTime> plan_time { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<byte> Delete_statute { get; set; }
    }
}
