//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class soud_x_client
    {
        public int soud_x_client_id { get; set; }
        public int soud_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public string plna_moc { get; set; }
        public Nullable<int> document_type { get; set; }
        public string insert_user { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string delete_user { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public Nullable<int> delete_statute { get; set; }
    }
}
