//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class splatka
    {
        public int splatka_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public string cislo_smlouvy { get; set; }
        public Nullable<int> cislo_splatky { get; set; }
        public string typ_splatky { get; set; }
        public Nullable<System.DateTime> datum_splatky { get; set; }
        public double vyse_splatky { get; set; }
        public double zaplaceno { get; set; }
        public Nullable<System.DateTime> datum_platby { get; set; }
        public Nullable<int> typ_zaznamu { get; set; }
        public System.DateTime insert_date { get; set; }
        public int delete_statute { get; set; }
        public string Insert_user { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
    
        public virtual @case @case { get; set; }
    }
}
