//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tables_desc_items
    {
        public int tables_desc_items_id { get; set; }
        public Nullable<int> tables_desc_id { get; set; }
        public string item_name { get; set; }
        public string data_type { get; set; }
        public Nullable<int> lenght { get; set; }
        public string default_value { get; set; }
        public Nullable<short> refference { get; set; }
        public Nullable<short> is_identity { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    
        public virtual tables_desc tables_desc { get; set; }
    }
}
