//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_transfer_payment
    {
        public int temp_transfer_payment_id { get; set; }
        public Nullable<int> payment_breakdown_id { get; set; }
        public Nullable<decimal> payed_capital { get; set; }
        public Nullable<decimal> payed_capital_to_transfer { get; set; }
        public Nullable<decimal> payed_delay_charge { get; set; }
        public Nullable<decimal> payed_delay_charge_to_transfer { get; set; }
        public Nullable<decimal> payed_administrative_assessment { get; set; }
        public Nullable<decimal> payed_administrative_assessment_to_transfer { get; set; }
        public Nullable<decimal> payed_plus_money { get; set; }
        public Nullable<decimal> payed_plus_money_to_transfer { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public string invoice_number { get; set; }
        public Nullable<System.DateTime> date_issued { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<decimal> original_capital { get; set; }
        public Nullable<decimal> actual_capital { get; set; }
        public Nullable<decimal> delay_charge { get; set; }
        public string invoice_text { get; set; }
        public string description { get; set; }
        public string insert_user { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    }
}
