//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_check_case
    {
        public int temp_check_case_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public string ref_number { get; set; }
        public string client_ref_number { get; set; }
        public Nullable<decimal> actual_capital { get; set; }
        public Nullable<decimal> client_actual_capital { get; set; }
        public Nullable<byte> @checked { get; set; }
        public string check_statute { get; set; }
    }
}
