//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_pay2
    {
        public string csv_ref { get; set; }
        public decimal pay_value { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
    }
}
