//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class unique_doc_group_sequence
    {
        public int unique_doc_group_sequence_id { get; set; }
        public string tmp { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
    }
}
