//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_log
    {
        public int user_log_id { get; set; }
        public Nullable<int> swclient_id { get; set; }
        public string log_type { get; set; }
        public Nullable<int> table_id { get; set; }
        public string comment { get; set; }
        public string @params { get; set; }
        public string insert_user { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public int result { get; set; }
        public string result_description { get; set; }
        public Nullable<int> SPID { get; set; }
        public Nullable<int> input_id { get; set; }
        public Nullable<int> input_type_id { get; set; }
    }
}
