//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vat
    {
        public int vat_id { get; set; }
        public int vat_type_id { get; set; }
        public double rate { get; set; }
        public System.DateTime date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string insert_user { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string delete_user { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public int delete_statute { get; set; }
        public Nullable<double> rate_div_100_plus_1 { get; set; }
        public Nullable<double> rate_div_100 { get; set; }
    }
}
