//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_bs_ustni_skaly_obdobi
    {
        public Nullable<int> case_id { get; set; }
        public string @operator { get; set; }
        public System.DateTime datum { get; set; }
        public Nullable<System.DateTime> konec { get; set; }
    }
}
