//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_print_aplications_doc
    {
        public int print_aplications_doc_id { get; set; }
        public string print_aplications_doc_name { get; set; }
        public int print_aplications_id { get; set; }
        public int report_data_template_id { get; set; }
        public int report_template_id { get; set; }
        public string xml_id { get; set; }
        public Nullable<short> print_aplications_doc_order { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
