//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_sucess_on_each_casepackage
    {
        public Nullable<decimal> pc { get; set; }
        public int CasePackage_ID { get; set; }
        public Nullable<int> client_id { get; set; }
        public int report_id { get; set; }
        public Nullable<int> mesicu { get; set; }
        public Nullable<decimal> oc { get; set; }
        public Nullable<decimal> procento { get; set; }
    }
}
