//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_payment_reported
    {
        public int payment_reported_id { get; set; }
        public Nullable<int> report_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<int> payment_breakdown_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<short> bank_id { get; set; }
        public Nullable<int> bank_account_id { get; set; }
        public string client_ref_number { get; set; }
        public Nullable<decimal> payed_capital { get; set; }
        public Nullable<decimal> payed_delay_charge { get; set; }
        public Nullable<decimal> payed_administrative_assessment { get; set; }
        public Nullable<decimal> payed_plus_money { get; set; }
        public string produkt { get; set; }
        public string cis_fakt { get; set; }
        public string datum_posl { get; set; }
        public string dluh { get; set; }
        public Nullable<decimal> dluhx { get; set; }
        public string kod { get; set; }
        public string platba_kapital { get; set; }
        public string platba_uroku { get; set; }
        public Nullable<System.DateTime> recipt_datex { get; set; }
        public string recipt_date { get; set; }
        public Nullable<byte> to_invoice { get; set; }
        public Nullable<byte> to_transfer { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
