//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_libs_items
    {
        public int libs_items_id { get; set; }
        public Nullable<int> libs_id { get; set; }
        public Nullable<int> libs_main_libs_id { get; set; }
        public string libs_main_lib_value { get; set; }
        public string lib_value { get; set; }
        public string lib_display_text { get; set; }
        public Nullable<int> lib_order { get; set; }
        public string datatype { get; set; }
        public Nullable<int> lenght { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
