//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_debtor_splitter_get_cases
    {
        public int case_x_debtor_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<long> ref_number { get; set; }
        public Nullable<int> debtor_id { get; set; }
        public Nullable<int> debtor_category_id { get; set; }
        public byte delete_statute { get; set; }
        public Nullable<byte> case_statute_id { get; set; }
    }
}
