//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_klient_success_a
    {
        public Nullable<int> CISLO_BATCHE { get; set; }
        public Nullable<int> KLIENT { get; set; }
        public Nullable<int> PREDANO_PRIPADU { get; set; }
        public Nullable<decimal> PREDANY_KAPITAL { get; set; }
        public Nullable<decimal> PREDANY_UROK { get; set; }
        public Nullable<System.DateTime> DATUM_PREDANI { get; set; }
        public int VYMOZENO_PRIPADU { get; set; }
        public decimal VYMOZENY_KAPITAL { get; set; }
        public decimal VYMOZENY_UROK { get; set; }
        public Nullable<decimal> USPESNOST_KAPITAL { get; set; }
        public Nullable<decimal> USPESNOST_KAP___UROK { get; set; }
        public Nullable<decimal> USPESNOST_KAP___UROK2 { get; set; }
        public int PLNEP___VYMOZENO_PRIPADU { get; set; }
        public decimal PLNEP___VYMOZENY_KAPITAL { get; set; }
        public decimal PLNEP___VYMOZENY_UROK { get; set; }
        public int SKAL___VYMOZENO_PRIPADU { get; set; }
        public decimal SKAL___VYMOZENY_KAPITAL { get; set; }
        public decimal SKAL___VYMOZENY_UROK { get; set; }
    }
}
