//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_print_invoice_report
    {
        public int vorder { get; set; }
        public Nullable<int> prints_spool_send_info_id { get; set; }
        public string type { get; set; }
        public Nullable<int> pocet { get; set; }
        public Nullable<int> pages_count { get; set; }
        public Nullable<int> prints_package_id { get; set; }
    }
}
