//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_klient_success3
    {
        public Nullable<int> CISLO_BATCHE { get; set; }
        public Nullable<int> KLIENT { get; set; }
        public int VYMOZENO_PRIPADU { get; set; }
        public decimal VYMOZENY_KAPITAL { get; set; }
        public decimal VYMOZENY_UROK { get; set; }
    }
}
