//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_statusy_MBAF_skupiny
    {
        public int case_id { get; set; }
        public int uhrazeno_zcela { get; set; }
        public int uzavreno_nz_klienta { get; set; }
        public int uhrazeno_castecne_skal { get; set; }
        public int uhrazeno_castecne_rozplaceno { get; set; }
        public int uhrazeno_castecne_inspektor { get; set; }
        public int neuhrazeno_nic_skal { get; set; }
        public int neuhrazeno_nic_upominani { get; set; }
        public int neuhrazeno_nic_dohledani { get; set; }
        public int neuhrazeno_nic_inspektor { get; set; }
        public int nepodarilo_se_kontaktovat { get; set; }
        public int umrti { get; set; }
        public int cekarna { get; set; }
        public int nebude_platit { get; set; }
        public int vezeni { get; set; }
        public int insolvence { get; set; }
        public int ostatni { get; set; }
    }
}
