//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Copmany_and_Full_telecom
    {
        public int Company_id { get; set; }
        public string Company_name { get; set; }
        public string Company_ico { get; set; }
        public string Company_dic { get; set; }
        public string Company_legal_form { get; set; }
        public Nullable<byte> Company_id_statute { get; set; }
        public string company_description { get; set; }
        public Nullable<int> CxT_id { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Source { get; set; }
        public Nullable<int> Telecom_id { get; set; }
        public Nullable<short> Telecom_Typ { get; set; }
        public string Area_code { get; set; }
        public string Local_code { get; set; }
        public string Phone_number { get; set; }
        public string Line_number { get; set; }
        public string telecom_Text1 { get; set; }
        public string telecom_Text2 { get; set; }
        public Nullable<byte> telecom_id_statute { get; set; }
        public string C_Insert_user { get; set; }
        public System.DateTime C_Insert_date { get; set; }
        public string C_Update_user { get; set; }
        public Nullable<System.DateTime> C_Update_date { get; set; }
        public string C_Delete_user { get; set; }
        public Nullable<System.DateTime> C_Delete_date { get; set; }
        public byte C_Delete_statute { get; set; }
        public string CxT_Insert_user { get; set; }
        public Nullable<System.DateTime> CxT_Insert_date { get; set; }
        public string CxT_Update_user { get; set; }
        public Nullable<System.DateTime> CxT_Update_date { get; set; }
        public string CxT_Delete_user { get; set; }
        public Nullable<System.DateTime> CxT_Delete_date { get; set; }
        public Nullable<byte> CxT_Delete_statute { get; set; }
        public string T_Insert_user { get; set; }
        public Nullable<System.DateTime> T_Insert_date { get; set; }
        public string T_Update_user { get; set; }
        public Nullable<System.DateTime> T_Update_date { get; set; }
        public string T_Delete_user { get; set; }
        public Nullable<System.DateTime> T_Delete_date { get; set; }
        public Nullable<byte> T_Delete_statute { get; set; }
        public string CxT_description { get; set; }
    }
}
