//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_active_operator_denni
    {
        public string @operator { get; set; }
        public Nullable<int> den { get; set; }
        public Nullable<int> mesic { get; set; }
        public Nullable<int> rok { get; set; }
        public int O_TEL_JO { get; set; }
        public int O_TEL_NE { get; set; }
        public int P_TEL { get; set; }
        public int O_SMS { get; set; }
        public int P_SMS { get; set; }
        public int O_MAFA { get; set; }
        public int P_MAFA { get; set; }
        public int O_ZAS { get; set; }
        public int P_ZAS { get; set; }
        public int T_TEL { get; set; }
        public int T_SMS { get; set; }
        public int T_MAFA { get; set; }
        public int T_ZAS { get; set; }
        public int T_VSE { get; set; }
    }
}
