//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_client_full
    {
        public int client_id { get; set; }
        public Nullable<int> client_type_id { get; set; }
        public string client_type { get; set; }
        public Nullable<int> Persons_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Company_name { get; set; }
        public string Company_short_name { get; set; }
        public string Company_ico { get; set; }
        public string Company_dic { get; set; }
        public string Company_legal_form { get; set; }
        public Nullable<byte> Company_id_statute { get; set; }
        public Nullable<int> PxA_id { get; set; }
        public Nullable<int> CxA_id { get; set; }
        public Nullable<int> contact_Persons_id { get; set; }
        public Nullable<int> contact2_Persons_id { get; set; }
    }
}
