//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_payments_ebanka_POSTA
    {
        public string account_number { get; set; }
        public Nullable<int> bank_statement_number { get; set; }
        public Nullable<int> statement_date { get; set; }
        public Nullable<int> payment_number { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_variable_symbol { get; set; }
        public Nullable<long> payment_specific_symbol { get; set; }
        public Nullable<decimal> payment_money { get; set; }
        public string variable_symnbol { get; set; }
        public string konstant_sysmbol { get; set; }
        public string specific_symbol { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> item_number { get; set; }
        public Nullable<decimal> payed_capital_czk { get; set; }
        public Nullable<decimal> payed_delay_charge { get; set; }
        public Nullable<decimal> payed_administrative_assessment { get; set; }
        public Nullable<decimal> payed_plus_money { get; set; }
        public int client_id { get; set; }
        public string Company_name { get; set; }
    }
}
