//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_postal_order
    {
        public int postal_order_id { get; set; }
        public Nullable<int> postal_order_type_id { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> installment_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public string bank_account_number_owner_name { get; set; }
        public string bank_account_number_owner_street { get; set; }
        public string bank_account_number_owner_city { get; set; }
        public string bank_account_number_owner_zip { get; set; }
        public string bank_account { get; set; }
        public string bank { get; set; }
        public string tr_code { get; set; }
        public string postziro_code { get; set; }
        public string postziro_bank { get; set; }
        public string S_code { get; set; }
        public string Persons_title { get; set; }
        public string Persons_firstname { get; set; }
        public string Persons_surname { get; set; }
        public string Address_cpop { get; set; }
        public string Address_street { get; set; }
        public string Address_city { get; set; }
        public string Address_zip { get; set; }
        public string VS { get; set; }
        public string SS { get; set; }
        public string KS { get; set; }
        public Nullable<decimal> kc { get; set; }
        public Nullable<decimal> hal { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<byte> Delete_statute { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string j1 { get; set; }
        public string j2 { get; set; }
        public string j3 { get; set; }
        public string j4 { get; set; }
        public string j5 { get; set; }
        public string j6 { get; set; }
        public string j7 { get; set; }
        public string j8 { get; set; }
        public string j9 { get; set; }
        public string j10 { get; set; }
        public string j11 { get; set; }
        public string j12 { get; set; }
        public string j13 { get; set; }
        public string j14 { get; set; }
        public string j15 { get; set; }
        public string j16 { get; set; }
        public string j17 { get; set; }
        public string p1 { get; set; }
        public string p2 { get; set; }
        public string p3 { get; set; }
        public string p4 { get; set; }
        public string p5 { get; set; }
        public string p6 { get; set; }
        public string p7 { get; set; }
        public string p8 { get; set; }
        public string p9 { get; set; }
        public string p10 { get; set; }
        public string p11 { get; set; }
        public string p12 { get; set; }
        public string p13 { get; set; }
        public string p14 { get; set; }
        public string p15 { get; set; }
        public string p16 { get; set; }
        public string p17 { get; set; }
        public string ul1 { get; set; }
        public string ul2 { get; set; }
        public string ul3 { get; set; }
        public string ul4 { get; set; }
        public string ul5 { get; set; }
        public string ul6 { get; set; }
        public string ul7 { get; set; }
        public string ul8 { get; set; }
        public string ul9 { get; set; }
        public string ul10 { get; set; }
        public string ul11 { get; set; }
        public string ul12 { get; set; }
        public string ul13 { get; set; }
        public string ul14 { get; set; }
        public string ul15 { get; set; }
        public string ul16 { get; set; }
        public string ul17 { get; set; }
        public string m1 { get; set; }
        public string m2 { get; set; }
        public string m3 { get; set; }
        public string m4 { get; set; }
        public string m5 { get; set; }
        public string m6 { get; set; }
        public string m7 { get; set; }
        public string m8 { get; set; }
        public string m9 { get; set; }
        public string m10 { get; set; }
        public string m11 { get; set; }
        public string m12 { get; set; }
        public string m13 { get; set; }
        public string m14 { get; set; }
        public string m15 { get; set; }
        public string m16 { get; set; }
        public string m17 { get; set; }
        public string psc1 { get; set; }
        public string psc2 { get; set; }
        public string psc3 { get; set; }
        public string psc4 { get; set; }
        public string psc5 { get; set; }
        public string kb1 { get; set; }
        public string kb2 { get; set; }
        public string kb3 { get; set; }
        public string kb4 { get; set; }
        public string ks1 { get; set; }
        public string ks2 { get; set; }
        public string ks3 { get; set; }
        public string ks4 { get; set; }
        public string VS1 { get; set; }
        public string VS2 { get; set; }
        public string VS3 { get; set; }
        public string VS4 { get; set; }
        public string VS5 { get; set; }
        public string VS6 { get; set; }
        public string VS7 { get; set; }
        public string VS8 { get; set; }
        public string VS9 { get; set; }
        public string VS10 { get; set; }
        public string SS1 { get; set; }
        public string SS2 { get; set; }
        public string SS3 { get; set; }
        public string SS4 { get; set; }
        public string SS5 { get; set; }
        public string SS6 { get; set; }
        public string SS7 { get; set; }
        public string SS8 { get; set; }
        public string SS9 { get; set; }
        public string SS10 { get; set; }
        public string u1 { get; set; }
        public string u2 { get; set; }
        public string u3 { get; set; }
        public string u4 { get; set; }
        public string u5 { get; set; }
        public string u6 { get; set; }
        public string u7 { get; set; }
        public string u8 { get; set; }
        public string u9 { get; set; }
        public string u10 { get; set; }
        public string u11 { get; set; }
        public string u12 { get; set; }
        public string u13 { get; set; }
        public string u14 { get; set; }
        public string u15 { get; set; }
        public string u16 { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string c4 { get; set; }
        public string c5 { get; set; }
        public string c6 { get; set; }
        public string c7 { get; set; }
        public string c8 { get; set; }
        public string h1 { get; set; }
        public string h2 { get; set; }
        public string s1 { get; set; }
        public string s2 { get; set; }
        public string tr1 { get; set; }
        public string tr2 { get; set; }
        public string tr3 { get; set; }
    }
}
