//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_trzeb_po_mesicich
    {
        public string client { get; set; }
        public string mesic_name { get; set; }
        public Nullable<decimal> zaplaceno { get; set; }
        public byte typ_fa { get; set; }
        public string obdobi { get; set; }
        public Nullable<int> rr { get; set; }
        public Nullable<int> mes { get; set; }
    }
}
