//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_PxC_full_company
    {
        public int PxC_id { get; set; }
        public Nullable<byte> type { get; set; }
        public string PxC_Type { get; set; }
        public string PxC_Type_status { get; set; }
        public string Persons_firstname { get; set; }
        public string Persons_surname { get; set; }
        public string Persons_born_number { get; set; }
        public Nullable<System.DateTime> validity_from { get; set; }
        public Nullable<System.DateTime> validity_to { get; set; }
        public string description { get; set; }
        public Nullable<byte> Status { get; set; }
        public int Persons_id { get; set; }
        public int Company_id { get; set; }
        public string cpop { get; set; }
        public string cor { get; set; }
        public string Address_street { get; set; }
        public string Address_street2 { get; set; }
        public string Address_village { get; set; }
        public string Address_city { get; set; }
        public string Address_zip { get; set; }
        public string Address_Country { get; set; }
        public string Address_District { get; set; }
        public string Address_Region { get; set; }
        public Nullable<byte> Address_statute { get; set; }
    }
}
