//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_payment_vs_bank_statement_breakdown_item_breakdown
    {
        public int payment_id { get; set; }
        public int bank_statement_breakdown_item_breakdown_id { get; set; }
        public Nullable<decimal> payed_capital { get; set; }
        public Nullable<decimal> payed_delay_charge { get; set; }
        public Nullable<decimal> payed_administrative_assessment { get; set; }
        public Nullable<decimal> payed_plus_money { get; set; }
        public Nullable<decimal> payment { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<decimal> diferences { get; set; }
    }
}
