//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_print_aplications
    {
        public int print_aplications_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> casepackage_id { get; set; }
        public string name { get; set; }
        public string report_name { get; set; }
        public Nullable<int> languague { get; set; }
        public Nullable<int> print_aplication_type_id { get; set; }
        public Nullable<int> paper_orientation { get; set; }
        public Nullable<int> default_paper { get; set; }
        public Nullable<int> duplex { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public int contact_status_type_id { get; set; }
        public Nullable<int> letter_no { get; set; }
    }
}
