//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Persons_and_Full_telecom_phone_with_index
    {
        public int Persons_id { get; set; }
        public Nullable<int> Telecom_id { get; set; }
        public Nullable<int> PxT_id { get; set; }
        public Nullable<short> Type { get; set; }
        public string type_text { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Source { get; set; }
        public string source_text { get; set; }
        public Nullable<short> Telecom_Typ { get; set; }
        public string Area_code { get; set; }
        public string Local_code { get; set; }
        public string Phone_number { get; set; }
        public string Line_number { get; set; }
        public Nullable<byte> telecom_id_statute { get; set; }
        public string telecom_id_statute_text { get; set; }
        public string telecom_Text1 { get; set; }
        public string PxT_description { get; set; }
        public int count1 { get; set; }
        public int count2 { get; set; }
        public string time_zone { get; set; }
    }
}
