//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_debtor_splitter_get_relations
    {
        public int pxc_id { get; set; }
        public int persons_id { get; set; }
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string company_ico { get; set; }
        public byte delete_statute { get; set; }
    }
}
