//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_show_all_payment_reported_with_error
    {
        public Nullable<int> case_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public int payment_breakdown_id { get; set; }
        public int payment_reported_id { get; set; }
        public Nullable<decimal> payed_capital { get; set; }
        public Nullable<decimal> payed_capital_r { get; set; }
        public Nullable<decimal> payed_delay_charge { get; set; }
        public Nullable<decimal> payed_delay_charge_r { get; set; }
    }
}
