//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_CasePackage
    {
        public int CasePackage_ID { get; set; }
        public Nullable<int> Contract_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> casepackage_ref_number { get; set; }
        public Nullable<short> casepackage_type { get; set; }
        public Nullable<int> assignment_date { get; set; }
        public Nullable<int> administrative_assessment_type_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> mail_sequence_id { get; set; }
        public Nullable<int> operator_group_id { get; set; }
        public Nullable<System.DateTime> MBA_delivery_date { get; set; }
        public Nullable<byte> provission { get; set; }
        public Nullable<System.DateTime> letter_no1_date { get; set; }
        public Nullable<System.DateTime> letter_no2_date { get; set; }
        public Nullable<System.DateTime> letter_no3_date { get; set; }
        public Nullable<System.DateTime> letter_no4_date { get; set; }
        public Nullable<System.DateTime> letter_no5_date { get; set; }
        public string Description { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public short casepackage_status_id { get; set; }
        public bool set_administrative_assessment { get; set; }
        public string client_package_number { get; set; }
    }
}
