//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_case_return
    {
        public int case_return_id { get; set; }
        public Nullable<int> case_return_package_id { get; set; }
        public Nullable<System.DateTime> case_return_date { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public string ref_number { get; set; }
        public string client_ref_number { get; set; }
        public string client_return_code { get; set; }
        public Nullable<int> return_code_id { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
