//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_payments_megafon
    {
        public Nullable<int> ID_отчета { get; set; }
        public System.DateTime Дата_отчета { get; set; }
        public string ФИО_должника { get; set; }
        public Nullable<long> Ref_number_MBA { get; set; }
        public string Ref_number_Клиента { get; set; }
        public string Номер_счета { get; set; }
        public string Название_счета__долг_ { get; set; }
        public Nullable<System.DateTime> Дата_образования_задолженности { get; set; }
        public Nullable<decimal> Первоначальный_основной_долг__капитал_ { get; set; }
        public Nullable<System.DateTime> Дата_получения_дела_в_МБА { get; set; }
        public Nullable<decimal> Общая_сумма_долга__переданная_МБА { get; set; }
        public Nullable<decimal> Платеж_основной_долг__капитал_ { get; set; }
        public Nullable<decimal> Платеж_пени { get; set; }
        public Nullable<decimal> Платеж_переплата { get; set; }
        public Nullable<System.DateTime> Платеж_дата { get; set; }
        public int Платеж_на_счет_клиента { get; set; }
        public Nullable<decimal> К_переводу { get; set; }
        public Nullable<int> ID_счета__МБА_ { get; set; }
        public Nullable<int> Просрочка { get; set; }
        public Nullable<int> Ставка_вознаграждения____ { get; set; }
        public Nullable<decimal> Вознаграждение_без_НДС__руб__ { get; set; }
        public Nullable<decimal> Вознаграждение_с_учетом_НДС__руб__ { get; set; }
    }
}
