//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_urgence_pravnich_moci
    {
        public int case_id { get; set; }
        public string soud { get; set; }
        public string cj_rozhodnuti { get; set; }
        public string ze_dne { get; set; }
        public Nullable<long> naše_značka { get; set; }
        public string žalovaný { get; set; }
        public string datum_narození___IČO { get; set; }
    }
}
