//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_inspector_breakdown2008
    {
        public int cislo_dluznika { get; set; }
        public string inspector_name { get; set; }
        public Nullable<long> ref_number { get; set; }
        public string client_ref_number { get; set; }
        public string prijmeni { get; set; }
        public string jmeno { get; set; }
        public string ulice { get; set; }
        public string cislo { get; set; }
        public string obec { get; set; }
        public string psc { get; set; }
        public Nullable<decimal> zaklad_dluhu { get; set; }
        public Nullable<decimal> urok { get; set; }
        public Nullable<decimal> admin_popl { get; set; }
        public Nullable<decimal> celkem { get; set; }
        public Nullable<System.DateTime> predano { get; set; }
        public Nullable<System.DateTime> ukonceno { get; set; }
    }
}
