//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_terminy_baliku
    {
        public Nullable<int> dni { get; set; }
        public int casepackage_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> casepackage_ref_number { get; set; }
        public Nullable<System.DateTime> mba_Delivery_date { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public Nullable<System.DateTime> spravny_den { get; set; }
        public string Description { get; set; }
    }
}
