//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_inspektor_case
    {
        public string INSPECTOR { get; set; }
        public Nullable<int> inspector_id { get; set; }
        public int ID_DLUZNIKA { get; set; }
        public Nullable<long> C_PRIPADU { get; set; }
        public string C_SMLOUVY { get; set; }
        public string PRIJMENI { get; set; }
        public string JMENO { get; set; }
        public Nullable<decimal> ALL_KAP { get; set; }
        public decimal ALL_VYMOZ { get; set; }
        public Nullable<decimal> ALL_AKTUAL { get; set; }
        public Nullable<System.DateTime> PREDANO { get; set; }
        public Nullable<decimal> C__USPESNOST { get; set; }
    }
}
