//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_payment_bank_statement_breakdown_diferences
    {
        public int bank_statement_breakdown_item_breakdown_id { get; set; }
        public Nullable<decimal> money_payment { get; set; }
        public Nullable<decimal> money { get; set; }
    }
}
