//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_success_batch_total_abs
    {
        public Nullable<decimal> ALL_KAP { get; set; }
        public decimal KAP_ORIG { get; set; }
        public decimal ADM_ORIG { get; set; }
        public decimal UROK_ORIG { get; set; }
        public Nullable<int> KAP_ORIG_PP { get; set; }
        public Nullable<int> KAP_ORIG_UZAVRENO { get; set; }
        public Nullable<int> KAP_ACTUAL_PP { get; set; }
        public Nullable<decimal> ALL_STORNO { get; set; }
        public decimal KAP_STORNO { get; set; }
        public decimal ADM_STORNO { get; set; }
        public decimal UROK_STORNO { get; set; }
        public Nullable<int> KAP_STORNO_PP { get; set; }
        public Nullable<decimal> ALL_VYMOZ { get; set; }
        public decimal KAP_VYMOZ { get; set; }
        public decimal ADM_VYMOZ { get; set; }
        public decimal UROK_VYMOZ { get; set; }
        public Nullable<int> KAP_VYMOZ_PP { get; set; }
        public Nullable<int> ADM_VYMOZ_PP { get; set; }
        public Nullable<int> UROK_VYMOZ_PP { get; set; }
        public Nullable<int> ALL_VYMOZ_PP { get; set; }
        public Nullable<decimal> ALL_AKTUAL { get; set; }
        public Nullable<decimal> KAP_AKTUAL { get; set; }
        public Nullable<decimal> ADM_AKTUAL { get; set; }
        public Nullable<decimal> UROK_AKTUAL { get; set; }
        public Nullable<decimal> ALL_USPESNOST { get; set; }
        public Nullable<decimal> KAP_USPESNOST { get; set; }
        public Nullable<decimal> ADM_USPESNOST { get; set; }
        public Nullable<decimal> UROK_USPESNOST { get; set; }
        public int operator1_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> mesic { get; set; }
        public Nullable<int> rok { get; set; }
        public string user_name { get; set; }
        public Nullable<int> casepackage_ref_number { get; set; }
    }
}
