//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_debtor_splitter_get_info
    {
        public int debtor_id { get; set; }
        public int persons_id { get; set; }
        public string persons_title { get; set; }
        public string persons_firstname { get; set; }
        public string persons_surname { get; set; }
        public string persons_end_title { get; set; }
        public string persons_born_name { get; set; }
        public string persons_vokativ { get; set; }
        public Nullable<byte> persons_gender { get; set; }
        public string persons_born_number { get; set; }
        public Nullable<byte> persons_born_day { get; set; }
        public Nullable<byte> persons_born_month { get; set; }
        public Nullable<short> persons_born_year { get; set; }
        public string persons_identity_card { get; set; }
    }
}
