//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_company
    {
        public int Company_id { get; set; }
        public string Company_name { get; set; }
        public string Company_ico { get; set; }
        public string Company_dic { get; set; }
        public string Company_legal_form { get; set; }
        public Nullable<byte> Company_id_statute { get; set; }
        public string company_description { get; set; }
        public string company_index_court { get; set; }
        public string company_index_court_file_identification { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
