//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_active_operator_motivace
    {
        public string @operator { get; set; }
        public Nullable<int> tyden { get; set; }
        public Nullable<int> rok { get; set; }
        public int users_id { get; set; }
        public int PP_TYD { get; set; }
        public int PP_TYD_NEKO { get; set; }
        public int AKCE_PP_ALL { get; set; }
        public Nullable<double> PP_TYD_USPECH { get; set; }
    }
}
