//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_task
    {
        public int task_id { get; set; }
        public int client_id { get; set; }
        public string Company_name { get; set; }
        public int casepackage_id { get; set; }
        public int casesubpackage_id { get; set; }
        public int case_id { get; set; }
        public Nullable<long> ref_number { get; set; }
        public int contact_id { get; set; }
        public int task_priority_id { get; set; }
        public Nullable<int> task_category_id { get; set; }
        public string task_category { get; set; }
        public Nullable<int> task_operation_id { get; set; }
        public string task_operation { get; set; }
        public string task_subject { get; set; }
        public Nullable<System.DateTime> task_requested_date { get; set; }
        public Nullable<System.DateTime> task_estimated_date { get; set; }
        public Nullable<byte> task_statute_id { get; set; }
        public string task_statute { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
    }
}
