//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_success_operator_batch
    {
        public string user_name { get; set; }
        public Nullable<int> mesic { get; set; }
        public Nullable<int> rok { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> casepackage_ref_number { get; set; }
        public Nullable<decimal> ALL_KAP { get; set; }
        public decimal KAP_ORIG { get; set; }
        public decimal ADM_ORIG { get; set; }
        public decimal UROK_ORIG { get; set; }
        public int ALL_KAP_PP { get; set; }
        public decimal ALL_STORNO { get; set; }
        public int ALL_STORNO_PP { get; set; }
        public decimal KAP_VYMOZ { get; set; }
        public decimal AP_VYMOZ { get; set; }
        public decimal UROK_VYMOZ { get; set; }
        public Nullable<decimal> ALL_VYMOZ { get; set; }
        public int ALL_VYMOZ_PP { get; set; }
    }
}
