//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_bank_statement_breakdown
    {
        public int bank_statement_breakdown_id { get; set; }
        public Nullable<int> bank_statement_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public Nullable<int> bank_account_id { get; set; }
        public Nullable<int> fix_bank_statement_breakdown_id { get; set; }
        public Nullable<int> fix_payment_id { get; set; }
        public Nullable<int> bank_statement_record_type_id { get; set; }
        public Nullable<int> bank_statement_number { get; set; }
        public Nullable<int> payment_number { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_description { get; set; }
        public string payment_bank_account_name { get; set; }
        public string payment_account_number { get; set; }
        public Nullable<System.DateTime> payument_write_off { get; set; }
        public Nullable<System.DateTime> payment_valuta { get; set; }
        public string payment_original_variable_symbol { get; set; }
        public Nullable<byte> payment_transaction_type_it { get; set; }
        public Nullable<long> payment_specific_symbol { get; set; }
        public string payment_variable_symbol { get; set; }
        public string payment_konstant_symbol { get; set; }
        public string invoice_number { get; set; }
        public Nullable<decimal> payment_money { get; set; }
        public Nullable<decimal> payment_bank_charge { get; set; }
        public Nullable<decimal> payment_bank_exchange { get; set; }
        public string payment_bank_notice { get; set; }
        public Nullable<short> payment_breakdown { get; set; }
        public Nullable<byte> payment_assigned { get; set; }
        public Nullable<byte> bank_statement_breakdown_statute_id { get; set; }
        public Nullable<System.DateTime> payment_assigment { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
