//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_bank_account
    {
        public int bank_account_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public string account_number { get; set; }
        public string bank_account_owner_name { get; set; }
        public string bank_account_owner_street { get; set; }
        public string bank_account_owner_city { get; set; }
        public string bank_account_owner_zip { get; set; }
        public string constant_symbol { get; set; }
        public string tr_code { get; set; }
        public string bank_number { get; set; }
        public string bank_name { get; set; }
        public Nullable<byte> bank_account_type_id { get; set; }
        public Nullable<int> main_bank_account_id { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
