//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_inspektor_payment
    {
        public string INSPECTOR { get; set; }
        public Nullable<long> C_PRIPADU { get; set; }
        public Nullable<int> KLIENT { get; set; }
        public Nullable<int> TYDEN { get; set; }
        public Nullable<int> ROK { get; set; }
        public decimal UHR_KAP { get; set; }
        public decimal UHR_UROK { get; set; }
        public decimal UHR_AP { get; set; }
        public decimal UHR_CELKEM { get; set; }
        public Nullable<decimal> ALL_PUV_KAP { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public string JMENO_DLUZNIKA { get; set; }
    }
}
