//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_rozdily_mezi_bankou_a_postou
    {
        public int bank_statement_breakdown_id { get; set; }
        public Nullable<decimal> rozpis { get; set; }
        public Nullable<decimal> platba { get; set; }
        public Nullable<decimal> rozdil { get; set; }
    }
}
