//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_show_all_payment_with_breakdown_with_error
    {
        public int payment_id { get; set; }
        public Nullable<decimal> capital { get; set; }
        public Nullable<decimal> capital_br { get; set; }
        public Nullable<decimal> delay_charge { get; set; }
        public Nullable<decimal> delay_charge_br { get; set; }
        public Nullable<decimal> administrative_assessment { get; set; }
        public Nullable<decimal> administrative_assessment_br { get; set; }
        public Nullable<decimal> plus_money { get; set; }
        public Nullable<decimal> plus_money_br { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    }
}
