//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_contact
    {
        public int contact_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> casepackage_id { get; set; }
        public Nullable<int> contract_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<byte> commission_id { get; set; }
        public Nullable<int> contact_type_id { get; set; }
        public Nullable<int> status_type_id { get; set; }
        public Nullable<System.DateTime> contact_date { get; set; }
        public Nullable<byte> operator_id { get; set; }
        public string contact_text { get; set; }
        public string contact_client_text { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
        public System.DateTime Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
    }
}
