//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_source_search_error
    {
        public int id_web_source_search_error { get; set; }
        public int libs_id { get; set; }
        public string lib_value { get; set; }
        public string @params { get; set; }
        public int robot_id { get; set; }
    
        public virtual robot robot { get; set; }
    }
}
