//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_administrative_assessment_settings_test
    {
        public int administrative_assessment_settings_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> Contract_id { get; set; }
        public Nullable<int> CasePackage_id { get; set; }
        public Nullable<int> Case_id { get; set; }
        public string description { get; set; }
        public Nullable<int> original_capital { get; set; }
        public Nullable<int> delay_charge { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<int> Delete_statute { get; set; }
    }
}
