//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_case_back_from_29102010_1200_backup
    {
        public int case_id { get; set; }
        public Nullable<int> CaseSubPackage_id { get; set; }
        public Nullable<int> CasePackage_id { get; set; }
        public Nullable<int> Contract_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> debtor_id { get; set; }
        public Nullable<int> guarantor_id { get; set; }
        public Nullable<byte> case_statute_id { get; set; }
        public Nullable<long> ref_number { get; set; }
        public string client_ref_number { get; set; }
        public string payment_var_symbol { get; set; }
        public string payment_specific_symbol { get; set; }
        public Nullable<int> bank_account_id { get; set; }
        public Nullable<int> operator1_id { get; set; }
        public Nullable<int> operator2_id { get; set; }
        public Nullable<int> operator_group_id { get; set; }
        public Nullable<decimal> original_administrative_assessment { get; set; }
        public Nullable<decimal> administrative_assessment { get; set; }
        public Nullable<byte> invoice { get; set; }
        public Nullable<int> date_issued { get; set; }
        public Nullable<int> due_date { get; set; }
        public Nullable<byte> currency_id { get; set; }
        public Nullable<decimal> original_exchange_rate { get; set; }
        public Nullable<decimal> original_capital { get; set; }
        public Nullable<decimal> original_capital_czk { get; set; }
        public Nullable<decimal> actual_capital { get; set; }
        public Nullable<decimal> delay_charge_to_date_of_delivery { get; set; }
        public Nullable<decimal> delay_charge_actual { get; set; }
        public string case_text { get; set; }
        public string description { get; set; }
        public string Insert_user { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Update_user { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Update_date_dbo { get; set; }
        public string Delete_user { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
        public Nullable<byte> Delete_statute { get; set; }
        public Nullable<int> debtor_id_old { get; set; }
        public Nullable<byte> department_id { get; set; }
        public Nullable<int> master_case_id { get; set; }
    }
}
