//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_PersonsStatisticTmp
    {
        public int person_id { get; set; }
        public int case_id { get; set; }
        public string person_name { get; set; }
        public string person_surname { get; set; }
        public Nullable<int> day_born { get; set; }
        public Nullable<int> month_born { get; set; }
        public Nullable<int> year_born { get; set; }
        public string region { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public Nullable<System.DateTime> date_delivery { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<decimal> original_capital { get; set; }
        public Nullable<decimal> payed_capital { get; set; }
        public Nullable<decimal> original_as { get; set; }
        public Nullable<decimal> payed_as { get; set; }
        public Nullable<int> last_letter_distance { get; set; }
        public Nullable<int> pre_last_letter_distance { get; set; }
        public Nullable<int> pre_last_letter_number { get; set; }
        public Nullable<int> is_1_letter { get; set; }
        public Nullable<int> is_2_letter { get; set; }
        public Nullable<int> is_3_letter { get; set; }
        public Nullable<int> is_4_letter { get; set; }
        public Nullable<int> is_5_letter { get; set; }
        public Nullable<int> is_6_letter { get; set; }
        public Nullable<int> is_7_letter { get; set; }
        public Nullable<int> is_8_letter { get; set; }
        public Nullable<int> day_from_due { get; set; }
    }
}
