//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_old_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_PersonsStatistic
    {
        public int person_id { get; set; }
        public string person_name { get; set; }
        public string person_surname { get; set; }
        public Nullable<int> person_gender { get; set; }
        public Nullable<int> day_born { get; set; }
        public Nullable<int> month_born { get; set; }
        public Nullable<int> year_born { get; set; }
        public string region { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public Nullable<System.DateTime> date_delivery { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<decimal> original_capital { get; set; }
        public Nullable<decimal> payed_capital { get; set; }
        public Nullable<decimal> original_as { get; set; }
        public Nullable<decimal> payed_as { get; set; }
        public Nullable<int> last_letter_distance { get; set; }
        public Nullable<int> pre_last_letter_distance { get; set; }
        public Nullable<int> pre_last_letter_number { get; set; }
        public Nullable<int> will_payed1 { get; set; }
        public Nullable<int> will_not_payed1 { get; set; }
        public Nullable<int> will_action1 { get; set; }
        public Nullable<int> in_call1 { get; set; }
        public Nullable<int> out_call1 { get; set; }
        public Nullable<int> will_payed2 { get; set; }
        public Nullable<int> will_not_payed2 { get; set; }
        public Nullable<int> will_action2 { get; set; }
        public Nullable<int> in_call2 { get; set; }
        public Nullable<int> out_call2 { get; set; }
        public Nullable<int> will_payed3 { get; set; }
        public Nullable<int> will_not_payed3 { get; set; }
        public Nullable<int> will_action3 { get; set; }
        public Nullable<int> in_call3 { get; set; }
        public Nullable<int> out_call3 { get; set; }
        public Nullable<int> will_payed4 { get; set; }
        public Nullable<int> will_not_payed4 { get; set; }
        public Nullable<int> will_action4 { get; set; }
        public Nullable<int> in_call4 { get; set; }
        public Nullable<int> out_call4 { get; set; }
        public Nullable<int> will_payed_all { get; set; }
        public Nullable<int> will_not_payed_all { get; set; }
        public Nullable<int> will_action_all { get; set; }
        public Nullable<int> is_1_letter { get; set; }
        public Nullable<int> is_2_letter { get; set; }
        public Nullable<int> is_3_letter { get; set; }
        public Nullable<int> is_4_letter { get; set; }
        public Nullable<int> is_5_letter { get; set; }
        public Nullable<int> is_6_letter { get; set; }
        public Nullable<int> is_7_letter { get; set; }
        public Nullable<int> is_8_letter { get; set; }
        public Nullable<int> is_dead { get; set; }
        public Nullable<int> is_sit { get; set; }
        public Nullable<int> live_in_city { get; set; }
        public Nullable<int> day_from_due { get; set; }
        public Nullable<int> is_telecom { get; set; }
        public string attribute { get; set; }
    }
}
