//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_application.MBAImportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodColumn", Namespace="http://schemas.datacontract.org/2004/07/mba_model")]
    [System.SerializableAttribute()]
    public partial class GoodColumn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mba_application.MBAImportService.ColumnHeader[] ColumnHeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mba_application.MBAImportService.ColumnHeader[] ColumnHeaders {
            get {
                return this.ColumnHeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnHeadersField, value) != true)) {
                    this.ColumnHeadersField = value;
                    this.RaisePropertyChanged("ColumnHeaders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((this.DeletedByField.Equals(value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColumnHeader", Namespace="http://schemas.datacontract.org/2004/07/mba_model")]
    [System.SerializableAttribute()]
    public partial class ColumnHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mba_application.MBAImportService.GoodColumn GoodColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodColumnIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mba_application.MBAImportService.GoodColumn GoodColumn {
            get {
                return this.GoodColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodColumnField, value) != true)) {
                    this.GoodColumnField = value;
                    this.RaisePropertyChanged("GoodColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodColumnId {
            get {
                return this.GoodColumnIdField;
            }
            set {
                if ((this.GoodColumnIdField.Equals(value) != true)) {
                    this.GoodColumnIdField = value;
                    this.RaisePropertyChanged("GoodColumnId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/mba_model")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((this.DeletedByField.Equals(value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InnerId {
            get {
                return this.InnerIdField;
            }
            set {
                if ((this.InnerIdField.Equals(value) != true)) {
                    this.InnerIdField = value;
                    this.RaisePropertyChanged("InnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportType", Namespace="http://schemas.datacontract.org/2004/07/mba_model")]
    [System.SerializableAttribute()]
    public partial class ImportType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MBAImportService.IImportService")]
    public interface IImportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GoodColumn", ReplyAction="http://tempuri.org/IImportService/GoodColumnResponse")]
        mba_application.MBAImportService.GoodColumn GoodColumn(string columnHeader);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IImportService/GoodColumn", ReplyAction="http://tempuri.org/IImportService/GoodColumnResponse")]
        System.IAsyncResult BeginGoodColumn(string columnHeader, System.AsyncCallback callback, object asyncState);
        
        mba_application.MBAImportService.GoodColumn EndGoodColumn(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GoodColumns", ReplyAction="http://tempuri.org/IImportService/GoodColumnsResponse")]
        mba_application.MBAImportService.GoodColumn[] GoodColumns();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IImportService/GoodColumns", ReplyAction="http://tempuri.org/IImportService/GoodColumnsResponse")]
        System.IAsyncResult BeginGoodColumns(System.AsyncCallback callback, object asyncState);
        
        mba_application.MBAImportService.GoodColumn[] EndGoodColumns(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/Clients", ReplyAction="http://tempuri.org/IImportService/ClientsResponse")]
        mba_application.MBAImportService.Client[] Clients();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IImportService/Clients", ReplyAction="http://tempuri.org/IImportService/ClientsResponse")]
        System.IAsyncResult BeginClients(System.AsyncCallback callback, object asyncState);
        
        mba_application.MBAImportService.Client[] EndClients(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/ImportTypes", ReplyAction="http://tempuri.org/IImportService/ImportTypesResponse")]
        mba_application.MBAImportService.ImportType[] ImportTypes();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IImportService/ImportTypes", ReplyAction="http://tempuri.org/IImportService/ImportTypesResponse")]
        System.IAsyncResult BeginImportTypes(System.AsyncCallback callback, object asyncState);
        
        mba_application.MBAImportService.ImportType[] EndImportTypes(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImportServiceChannel : mba_application.MBAImportService.IImportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoodColumnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GoodColumnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public mba_application.MBAImportService.GoodColumn Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((mba_application.MBAImportService.GoodColumn)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoodColumnsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GoodColumnsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public mba_application.MBAImportService.GoodColumn[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((mba_application.MBAImportService.GoodColumn[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ClientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public mba_application.MBAImportService.Client[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((mba_application.MBAImportService.Client[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ImportTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public mba_application.MBAImportService.ImportType[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((mba_application.MBAImportService.ImportType[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportServiceClient : System.ServiceModel.ClientBase<mba_application.MBAImportService.IImportService>, mba_application.MBAImportService.IImportService {
        
        private BeginOperationDelegate onBeginGoodColumnDelegate;
        
        private EndOperationDelegate onEndGoodColumnDelegate;
        
        private System.Threading.SendOrPostCallback onGoodColumnCompletedDelegate;
        
        private BeginOperationDelegate onBeginGoodColumnsDelegate;
        
        private EndOperationDelegate onEndGoodColumnsDelegate;
        
        private System.Threading.SendOrPostCallback onGoodColumnsCompletedDelegate;
        
        private BeginOperationDelegate onBeginClientsDelegate;
        
        private EndOperationDelegate onEndClientsDelegate;
        
        private System.Threading.SendOrPostCallback onClientsCompletedDelegate;
        
        private BeginOperationDelegate onBeginImportTypesDelegate;
        
        private EndOperationDelegate onEndImportTypesDelegate;
        
        private System.Threading.SendOrPostCallback onImportTypesCompletedDelegate;
        
        public ImportServiceClient() {
        }
        
        public ImportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GoodColumnCompletedEventArgs> GoodColumnCompleted;
        
        public event System.EventHandler<GoodColumnsCompletedEventArgs> GoodColumnsCompleted;
        
        public event System.EventHandler<ClientsCompletedEventArgs> ClientsCompleted;
        
        public event System.EventHandler<ImportTypesCompletedEventArgs> ImportTypesCompleted;
        
        public mba_application.MBAImportService.GoodColumn GoodColumn(string columnHeader) {
            return base.Channel.GoodColumn(columnHeader);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGoodColumn(string columnHeader, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGoodColumn(columnHeader, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public mba_application.MBAImportService.GoodColumn EndGoodColumn(System.IAsyncResult result) {
            return base.Channel.EndGoodColumn(result);
        }
        
        private System.IAsyncResult OnBeginGoodColumn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string columnHeader = ((string)(inValues[0]));
            return this.BeginGoodColumn(columnHeader, callback, asyncState);
        }
        
        private object[] OnEndGoodColumn(System.IAsyncResult result) {
            mba_application.MBAImportService.GoodColumn retVal = this.EndGoodColumn(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGoodColumnCompleted(object state) {
            if ((this.GoodColumnCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GoodColumnCompleted(this, new GoodColumnCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GoodColumnAsync(string columnHeader) {
            this.GoodColumnAsync(columnHeader, null);
        }
        
        public void GoodColumnAsync(string columnHeader, object userState) {
            if ((this.onBeginGoodColumnDelegate == null)) {
                this.onBeginGoodColumnDelegate = new BeginOperationDelegate(this.OnBeginGoodColumn);
            }
            if ((this.onEndGoodColumnDelegate == null)) {
                this.onEndGoodColumnDelegate = new EndOperationDelegate(this.OnEndGoodColumn);
            }
            if ((this.onGoodColumnCompletedDelegate == null)) {
                this.onGoodColumnCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGoodColumnCompleted);
            }
            base.InvokeAsync(this.onBeginGoodColumnDelegate, new object[] {
                        columnHeader}, this.onEndGoodColumnDelegate, this.onGoodColumnCompletedDelegate, userState);
        }
        
        public mba_application.MBAImportService.GoodColumn[] GoodColumns() {
            return base.Channel.GoodColumns();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGoodColumns(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGoodColumns(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public mba_application.MBAImportService.GoodColumn[] EndGoodColumns(System.IAsyncResult result) {
            return base.Channel.EndGoodColumns(result);
        }
        
        private System.IAsyncResult OnBeginGoodColumns(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGoodColumns(callback, asyncState);
        }
        
        private object[] OnEndGoodColumns(System.IAsyncResult result) {
            mba_application.MBAImportService.GoodColumn[] retVal = this.EndGoodColumns(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGoodColumnsCompleted(object state) {
            if ((this.GoodColumnsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GoodColumnsCompleted(this, new GoodColumnsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GoodColumnsAsync() {
            this.GoodColumnsAsync(null);
        }
        
        public void GoodColumnsAsync(object userState) {
            if ((this.onBeginGoodColumnsDelegate == null)) {
                this.onBeginGoodColumnsDelegate = new BeginOperationDelegate(this.OnBeginGoodColumns);
            }
            if ((this.onEndGoodColumnsDelegate == null)) {
                this.onEndGoodColumnsDelegate = new EndOperationDelegate(this.OnEndGoodColumns);
            }
            if ((this.onGoodColumnsCompletedDelegate == null)) {
                this.onGoodColumnsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGoodColumnsCompleted);
            }
            base.InvokeAsync(this.onBeginGoodColumnsDelegate, null, this.onEndGoodColumnsDelegate, this.onGoodColumnsCompletedDelegate, userState);
        }
        
        public mba_application.MBAImportService.Client[] Clients() {
            return base.Channel.Clients();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginClients(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginClients(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public mba_application.MBAImportService.Client[] EndClients(System.IAsyncResult result) {
            return base.Channel.EndClients(result);
        }
        
        private System.IAsyncResult OnBeginClients(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginClients(callback, asyncState);
        }
        
        private object[] OnEndClients(System.IAsyncResult result) {
            mba_application.MBAImportService.Client[] retVal = this.EndClients(result);
            return new object[] {
                    retVal};
        }
        
        private void OnClientsCompleted(object state) {
            if ((this.ClientsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ClientsCompleted(this, new ClientsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ClientsAsync() {
            this.ClientsAsync(null);
        }
        
        public void ClientsAsync(object userState) {
            if ((this.onBeginClientsDelegate == null)) {
                this.onBeginClientsDelegate = new BeginOperationDelegate(this.OnBeginClients);
            }
            if ((this.onEndClientsDelegate == null)) {
                this.onEndClientsDelegate = new EndOperationDelegate(this.OnEndClients);
            }
            if ((this.onClientsCompletedDelegate == null)) {
                this.onClientsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnClientsCompleted);
            }
            base.InvokeAsync(this.onBeginClientsDelegate, null, this.onEndClientsDelegate, this.onClientsCompletedDelegate, userState);
        }
        
        public mba_application.MBAImportService.ImportType[] ImportTypes() {
            return base.Channel.ImportTypes();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginImportTypes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginImportTypes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public mba_application.MBAImportService.ImportType[] EndImportTypes(System.IAsyncResult result) {
            return base.Channel.EndImportTypes(result);
        }
        
        private System.IAsyncResult OnBeginImportTypes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginImportTypes(callback, asyncState);
        }
        
        private object[] OnEndImportTypes(System.IAsyncResult result) {
            mba_application.MBAImportService.ImportType[] retVal = this.EndImportTypes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnImportTypesCompleted(object state) {
            if ((this.ImportTypesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ImportTypesCompleted(this, new ImportTypesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ImportTypesAsync() {
            this.ImportTypesAsync(null);
        }
        
        public void ImportTypesAsync(object userState) {
            if ((this.onBeginImportTypesDelegate == null)) {
                this.onBeginImportTypesDelegate = new BeginOperationDelegate(this.OnBeginImportTypes);
            }
            if ((this.onEndImportTypesDelegate == null)) {
                this.onEndImportTypesDelegate = new EndOperationDelegate(this.OnEndImportTypes);
            }
            if ((this.onImportTypesCompletedDelegate == null)) {
                this.onImportTypesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnImportTypesCompleted);
            }
            base.InvokeAsync(this.onBeginImportTypesDelegate, null, this.onEndImportTypesDelegate, this.onImportTypesCompletedDelegate, userState);
        }
    }
}
