//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace mba_ODataService.mbaf
{

    public partial class Users : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        DateTime fFreezed;
        public DateTime Freezed
        {
            get { return fFreezed; }
            set { SetPropertyValue<DateTime>("Freezed", ref fFreezed, value); }
        }
        string fLogin;
        [Size(SizeAttribute.Unlimited)]
        public string Login
        {
            get { return fLogin; }
            set { SetPropertyValue<string>("Login", ref fLogin, value); }
        }
        string fFirstName;
        [Size(SizeAttribute.Unlimited)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>("FirstName", ref fFirstName, value); }
        }
        string fMiddleName;
        [Size(SizeAttribute.Unlimited)]
        public string MiddleName
        {
            get { return fMiddleName; }
            set { SetPropertyValue<string>("MiddleName", ref fMiddleName, value); }
        }
        string fLastName;
        [Size(SizeAttribute.Unlimited)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>("LastName", ref fLastName, value); }
        }
        string fFullName;
        [Size(SizeAttribute.Unlimited)]
        public string FullName
        {
            get { return fFullName; }
            set { SetPropertyValue<string>("FullName", ref fFullName, value); }
        }
        string fEmail;
        [Size(SizeAttribute.Unlimited)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        byte[] fPhoto;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Photo
        {
            get { return fPhoto; }
            set { SetPropertyValue<byte[]>("Photo", ref fPhoto, value); }
        }
    }

}
