//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace mba_ODataService.mbaf
{

    public partial class UserActions : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Persistent("UserId")]
            public int UserId { get; set; }
            [Persistent("ActionId")]
            public int ActionId { get; set; }
            [Persistent("Created")]
            public DateTime Created { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
