//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mba_application.MBAUserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MBAUserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Permissions", ReplyAction="http://tempuri.org/IUserService/PermissionsResponse")]
        mba_model.Permission[] Permissions();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IUserService/Permissions", ReplyAction="http://tempuri.org/IUserService/PermissionsResponse")]
        System.IAsyncResult BeginPermissions(System.AsyncCallback callback, object asyncState);
        
        mba_model.Permission[] EndPermissions(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Users", ReplyAction="http://tempuri.org/IUserService/UsersResponse")]
        mba_model.User[] Users();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IUserService/Users", ReplyAction="http://tempuri.org/IUserService/UsersResponse")]
        System.IAsyncResult BeginUsers(System.AsyncCallback callback, object asyncState);
        
        mba_model.User[] EndUsers(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : mba_application.MBAUserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public mba_model.Permission[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((mba_model.Permission[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public mba_model.User[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((mba_model.User[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<mba_application.MBAUserService.IUserService>, mba_application.MBAUserService.IUserService {
        
        private BeginOperationDelegate onBeginPermissionsDelegate;
        
        private EndOperationDelegate onEndPermissionsDelegate;
        
        private System.Threading.SendOrPostCallback onPermissionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUsersDelegate;
        
        private EndOperationDelegate onEndUsersDelegate;
        
        private System.Threading.SendOrPostCallback onUsersCompletedDelegate;
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<PermissionsCompletedEventArgs> PermissionsCompleted;
        
        public event System.EventHandler<UsersCompletedEventArgs> UsersCompleted;
        
        public mba_model.Permission[] Permissions() {
            return base.Channel.Permissions();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPermissions(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPermissions(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public mba_model.Permission[] EndPermissions(System.IAsyncResult result) {
            return base.Channel.EndPermissions(result);
        }
        
        private System.IAsyncResult OnBeginPermissions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginPermissions(callback, asyncState);
        }
        
        private object[] OnEndPermissions(System.IAsyncResult result) {
            mba_model.Permission[] retVal = this.EndPermissions(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPermissionsCompleted(object state) {
            if ((this.PermissionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PermissionsCompleted(this, new PermissionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PermissionsAsync() {
            this.PermissionsAsync(null);
        }
        
        public void PermissionsAsync(object userState) {
            if ((this.onBeginPermissionsDelegate == null)) {
                this.onBeginPermissionsDelegate = new BeginOperationDelegate(this.OnBeginPermissions);
            }
            if ((this.onEndPermissionsDelegate == null)) {
                this.onEndPermissionsDelegate = new EndOperationDelegate(this.OnEndPermissions);
            }
            if ((this.onPermissionsCompletedDelegate == null)) {
                this.onPermissionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPermissionsCompleted);
            }
            base.InvokeAsync(this.onBeginPermissionsDelegate, null, this.onEndPermissionsDelegate, this.onPermissionsCompletedDelegate, userState);
        }
        
        public mba_model.User[] Users() {
            return base.Channel.Users();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUsers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUsers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public mba_model.User[] EndUsers(System.IAsyncResult result) {
            return base.Channel.EndUsers(result);
        }
        
        private System.IAsyncResult OnBeginUsers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginUsers(callback, asyncState);
        }
        
        private object[] OnEndUsers(System.IAsyncResult result) {
            mba_model.User[] retVal = this.EndUsers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUsersCompleted(object state) {
            if ((this.UsersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UsersCompleted(this, new UsersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UsersAsync() {
            this.UsersAsync(null);
        }
        
        public void UsersAsync(object userState) {
            if ((this.onBeginUsersDelegate == null)) {
                this.onBeginUsersDelegate = new BeginOperationDelegate(this.OnBeginUsers);
            }
            if ((this.onEndUsersDelegate == null)) {
                this.onEndUsersDelegate = new EndOperationDelegate(this.OnEndUsers);
            }
            if ((this.onUsersCompletedDelegate == null)) {
                this.onUsersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUsersCompleted);
            }
            base.InvokeAsync(this.onBeginUsersDelegate, null, this.onEndUsersDelegate, this.onUsersCompletedDelegate, userState);
        }
    }
}
